operable/cog

Dockerfile
mix.exs
mix.lock

* Updates dependencies in `mix.exs` to make sure they all use HTTPS instead of SSH to fetch.
* Uses operable/docker-base, simplifying the Dockerfile considerably
This solves the same problem as #284, but we'll take this iteration since it uses the operable/docker-base that wasn't publicly available when @sgerrand investigated.

Fix Cog's Dockerfile so the container can be built

---

lib/cog/models/bundle.ex
priv/repo/migrations/20160224180326_unique_bundle_names.exs
test/cog/rule_test.exs

Not having this was a complete oversight!
Changed some tests to both use the Bundle changeset, and not conflict
with the already-installed `operable` bundle.

Enforce unique bundle names in database

---

lib/cog/bundle/install.ex
lib/cog/models/command.ex
priv/repo/migrations/20160224184802_drop_command_versions.exs
test/cog/models/command_test.exs
test/cog/queries/command_test.exs
test/cog/rule_test.exs
test/support/database_test_setup.ex

Bundles will have versions soon, but commands are losing them now. There
should be no user-facing effects on this change, as we weren't really
using command versions anyway; they're vestigial from an earlier design.
See also https://github.com/operable/spanner/pull/41, but that is actually independent of this change, and not necessary for this to be merged.

Commands no longer have versions

---

lib/cog/models/permission.ex
lib/cog/models/role.ex
lib/cog/models/rule.ex
lib/cog/models/template.ex
lib/cog/models/token.ex

Converts all `Ecto.Changeset.cast/3` to `Ecto.Changeset.cast/4`. The builds were a tad noisy.

Convert deprecated `Ecto.Changeset.cast/3` to `Ecto.Changeset.cast/4`

---

test/integration/relay_test.exs

We now kill relay from an `on_exit` hook so processes don't stick around in-between test runs.

Properly kill relay after failed tests

---

lib/cog/command/command_resolver.ex
lib/cog/commands/alias/helpers.ex
lib/cog/commands/alias/ls.ex
lib/cog/models/command.ex
mix.exs
mix.lock
test/integration/alias_execution_test.exs
test/integration/commands/alias_test.exs

This commit adds support for Slack emojis as command aliases. It incorporates parser changes in Piper which allow alias names like `:shipit:` to be parsed and recognized as potential command or alias names.
The following changes were made to Cog:
- Slight tweak to `CommandResolver` to recognize names starting with `:`
as potential commands or aliases and look them up.
- Tweak to `Models.Command.split_name/1` to correctly split names like
`user::pager:` or `somebundle::thumbsup:` into bundle and command
parts.
- Added integration test to exercise emoji alias execution
Requires Piper PR [#10](https://github.com/operable/piper/pull/10)

Support Slack emojis as aliases

---

lib/cog/command/alias_expander.ex
lib/cog/command/pipeline/executor.ex
test/integration/command_test.exs

Commands were crashing when a variable was used to reference them.
example: `echo echo | $body[0] foo`
resolves #308

Command variable fix

---

lib/cog/command/bundle_cache.ex
lib/cog/command/command_sup.ex
lib/cog/command/pipeline/executor.ex
lib/cog/models/bundle.status.ex
lib/cog/relay/relays.ex
lib/cog/relay/tracker.ex
test/cog/relay/tracker_test.exs

Previously, `Cog.Relay.Relays` was tracking not only which relays were
running a given bundle, but also the enabled/disabled status of those
bundles. Now, it tracks only which relays run which bundles, and knows
nothing of the bundles' status.
Instead, the executor now factors in the bundle status when
determining which relay to dispatch to. If the bundle is disabled, we
can now return a more accurate error message to the user (previously,
it was confusing to say that no relays were running a bundle if some
relays actually _were_, but the bundle was just disabled).
To ease the database burden for these status checks, a new bundle
cache is introduced. It is similar to other caches we have, but
implemented to use generic functions as much as possible. Hopefully
this can be the basis of a …

Database is sole source of truth for bundle status 

---

lib/cog/commands/alias/helpers.ex
lib/cog/models/site_command_alias.ex
lib/cog/models/user_command_alias.ex
test/integration/commands/alias_test.exs

Return a clearer and better formatted error message when the name already in use error occurs during alias creation.
resolves #313

add a special db_error message when an alias name is already in use

---

docker-compose.yml

This sets the environment variable ERL_FLAGS="-smp enable". This allows Cog and Relay to execute using SMP and dirty schedulers.

Set ERL_FLAGS to use SMP and dirty schedulers

---

config/config.exs
lib/cog.ex
lib/cog/adapter.ex
lib/cog/adapters/config.ex
lib/cog/adapters/irc.ex
lib/cog/adapters/irc/config.ex
lib/cog/adapters/irc/connection.ex
lib/cog/adapters/irc/supervisor.ex
lib/cog/adapters/slack/supervisor.ex
mix.exs
mix.lock
priv/repo/migrations/20160301224759_add_irc_chat_provider.exs

The IRC adapter works. You can set options just as you'd expect which allows cog to connect to your IRC channel (currently only 1 channel is supported). Mentioned commands and spoken commands are supported, as well as user private message redirection.
Part of this PR was to take a fresh look at the new adapter refactor and see if it is well designed. I think the refactor has improved the interface but I think there are a few extra things we can add to make it easier to write adapters in the future:
* Remove `lookup_room` calls from the executor that pass along a string. This makes for some function definitions. We should instead implement it by having each adapter identify a string as a room or a user (used for redirection) and then having the executor call `lookup_room(name: room_name)` …

IRC adapter

---

lib/cog/adapters/config.ex
lib/cog/adapters/hipchat/api.ex
lib/cog/adapters/hipchat/config.ex
lib/cog/adapters/hipchat/connection.ex
lib/cog/adapters/hipchat/supervisor.ex
lib/cog/adapters/irc/config.ex
lib/cog/adapters/irc/supervisor.ex
test/cog/adapters/config_test.exs

Now if `Cog.Adapters.Config` is used to require keys or specifies types, the adapter will fail to startup when the config is invalid and any specific errors will be logged as errors. Here's an example of what happens if you forget to include HipChat's config.
```
2016-03-08T16:31:31.0519  (Cog.Adapters.Config:115) [error] Required key :mention_name was not provided
2016-03-08T16:31:31.0519  (Cog.Adapters.Config:115) [error] Required key :token was not provided
2016-03-08T16:31:31.0519  (Cog.Adapters.Config:115) [error] Required key :jid was not provided
2016-03-08T16:31:31.0519  (Cog.Adapters.Config:115) [error] Required key :password was not provided
2016-03-08T16:31:31.0519  (Cog.Adapters.Config:115) [error] Required key :rooms was not provided
2016-03-08T16:31:31.0535  () [info] …
```

Adapters log errors and then exit on failed configuration

---

lib/cog/queries/command.ex
test/cog/rule_ingestion_test.exs

`Cog.Queries.Command.options_for/1` wasn't used.
`Cog.Queries.Command.rules_for/1` was only used in a test, which is
now rewritten.

Remove some unused command-related queries

---

lib/cog/models/user.ex
priv/repo/migrations/20160309201354_first_name_last_name_optional.exs

The first and last names in the User model should be optional fields. We allow the database to accept null values for first and last names.
Fixes #362

Issue #362: Make first_name and last_name optional fields

---

GLOSSARY.md

This starts the basic of a glossary in the repo. This is something we've talked about a bit while moving forward in development and I wanted to get a structure started so that we could start adding to it.
Some of this information is already in the Wiki so you're probably asking yourself "Why would we move this into the repo?" I'm glad you asked!
1. Moving it into the repo allows it to be versioned alongside the code. As the code changes and new ideas and concepts are added and removed, this file can change with the code. It may fall out of date at periods, that inevitable but if properly maintained, you can look back at a previous release and understand the concepts that are particular to that release that may have changed in a newer release.
2. Wikis do not have any way of reviewing …

Add a basic glossary outline

---

lib/cog.ex

The application isn't ready to receive HTTP requests until we've
connected to the database and we've installed the embedded bundle, which
includes creating permissions necessary for bootstrapping. So, Ecto.Repo
and all bundle related processes need to have started before the
Endpoint process.

Start Endpoint process last in supervision tree

---

lib/cog/adapters/hipchat/api.ex
lib/cog/adapters/hipchat/connection.ex
lib/cog/adapters/hipchat/supervisor.ex
test/cog/adapters/hipchat/api_test.exs
test/support/adapters/hipchat/helpers.ex

We now validate the config and then also try to make an authenticated request when starting the HipChat.API process. To do that (and avoid having to cache the config) we converted the HipChat.API module into a GenServer so we have a good place to check the config and crash the entire Cog application as well as hold onto the config between API calls.

Check HipChat config when starting the HipChat Adapater

---

lib/cog/adapters/hipchat/api.ex

We had a couple of unexpected return values that were crashing the
Hipchat.API process. Those are now fixed and direct messages are working
again.

Fix bugs causing hipchat direct messages to fail

---

lib/cog.ex
lib/cog/adapter.ex
lib/cog/adapters/hipchat.ex
lib/cog/adapters/irc.ex
lib/cog/adapters/null.ex
lib/cog/adapters/slack.ex
lib/cog/adapters/slack/api.ex
lib/cog/adapters/slack/rtm_connector.ex
lib/cog/command/pipeline/executor.ex
test/support/adapters/test.ex

This commit separates room membership checks from room lookups. This is
achieved by adding a new public API function to the `Cog.Adapter`
behavior: `room_writeable?/1` which returns true when the bot is
permitted to send messages to a room, false when it's not, and an error
tuple for all other cases. All adapters except Slack always return true.
The Slack adapter returns true if the bot is a member of the room
otherwise false (or error if the API call fails). This allows us to
catch the case where a user redirects output to room(s) where their Cog
instance is not present.
The executor uses this check to detect invalid redirects.
Fixes #410

Decouple room lookup and membership check

---

lib/cog/command/pipeline/executor.ex

Trying to run a command from a deactivated bundle errored out with:
```
** Reason for termination = 
** {%Protocol.UndefinedError{description: nil, protocol: String.Chars,
value: %Cog.Models.Bundle{__meta__: #Ecto.Schema.Metadata<:loaded>,
commands: #Ecto.Association.NotLoaded<association :commands is not loaded>,
config_file: %{"bundle" => %{"name" => "graph"},
"commands" => [%{"documentation" => "graph --x=\"timestamp\" --y=\"total\" --format=<format> - Read JSON data piped from the previous command and turn it into a graph",
"enforcing" => false,
"executable" => "/Users/vanstee/Code/operable/graph/graph.rb",
"name" => "graph",
"options" => [%{"name" => "x", "required" => true, "type" => "string"},
%{"name" => "y", "required" => true, "type" => "string"},
%{"name" => "format", …
```

Fix interpolation of bundle name in deactivated bundle error

---

.gitignore
Makefile
mix.exs
mix.lock

Run `make coverage` to run tests, producing a coverage report. An
overview will be printed to the terminal, but open
`cover/excoveralls.html` for a more detailed report.
Does not (yet?) post anything to coveralls.io.

Add ExCoveralls for test coverage reporting

---

lib/cog/adapters/slack/api.ex
lib/cog/command/pipeline/executor.ex
test/integration/slack_test.exs

Removes the resolution code we had in place if a user redirected to
`foo`, as opposed to either `@foo` or `#foo`; now, you must be explicit.
Extracted the redirection error message out to a helper function to make
it a bit easier to reason about.
Fixes #210

Require @ and # for Slack redirect destinations

---

test/controllers/v1/token_controller_test.exs
web/controllers/v1/token_controller.ex

Previously, the controller would crash if either the username or password were not provided, or were nil.
Related to #371

Token controller handles missing or nil parameters

---

test/controllers/v1/group_membership_controller_test.exs
test/controllers/v1/permission_grant_controller_test.exs
test/controllers/v1/role_grant_controller_test.exs
web/controllers/v1/group_membership_controller.ex
web/controllers/v1/permission_controller.ex
web/controllers/v1/permission_grant_controller.ex
web/controllers/v1/role_grant_controller.ex
web/controllers/v1/token_controller.ex
web/views/bootstrap_view.ex
web/views/error_view.ex

Before this change there was an inconsistent struct usage for errors. Some changesets used `:errors`, while others used `:error`. This PR changes things such that Cog uses `:errors`, which is consistent with the Ecto.changeset.
Fixes #442

Use consistent errors param

---

test/controllers/v1/token_controller_test.exs
web/controllers/v1/token_controller.ex

This fixes the tests that are failing on master. The errors are stored using ":errors" instead 'f ":error".

Make Token controller use errors instead of error

---

config/config.exs
lib/cog/adapter.ex
lib/cog/adapters/hipchat.ex
lib/cog/adapters/irc.ex
lib/cog/adapters/irc/connection.ex
lib/cog/adapters/null.ex
lib/cog/adapters/slack.ex
lib/cog/adapters/slack/api.ex
lib/cog/command/user_permissions_cache.ex
lib/cog/commands/alias/ls.ex
lib/cog/commands/helpers.ex
lib/cog/models/chat_handle.ex
lib/cog/models/user_command_alias.ex
lib/cog/queries.ex
lib/cog/queries/alias.ex
lib/cog/queries/chat_handle.ex
lib/cog/queries/user.ex
lib/cog/support/model_utilities.ex
priv/repo/migrations/20160317183129_add_chat_provider_user_id_to_chat_handles.exs
test/cog/user_test.exs
test/controllers/v1/chat_handle_controller_test.exs
test/integration/redirect_test.exs
test/support/adapters/test.ex
test/support/adapters/test/helpers.ex
web/controllers/v1/chat_handle_controller.ex

We needed to lookup a user and their permissions with the internal id their chat provider users, since handles can be changed (or swaped) leading to someone stealing old permissions. Here's the break down of what changed:
Closes https://github.com/operable/cog/issues/353

Use provider user id to lookup cog user

---

lib/cog/adapters/null.ex
priv/repo/migrations/20160322222933_add_null_chat_provider.exs

This PR fixes the cogctl chat-handler creation test by adding the null chat adapter and stubbing a lookup_user function.
Fixes https://github.com/operable/cog/issues/456

Add null chat provider

---

lib/cog/adapter.ex
lib/cog/command/pipeline/executor.ex
lib/cog/command/pipeline/executor_sup.ex
lib/cog/command/pipeline/initializer.ex
test/support/adapters/test/helpers.ex

Previously the executor itself would create a unique ID for the pipeline
being executed. In order to facilitate better tracking for pipelines
that are initiated from external events (e.g., webhooks), we'll need to
externalize this ID generation. (this will allow us to correlate HTTP
request processing with the resulting pipeline).
Now the pipeline initializer creates the ID and passes it as an argument
to the new executor process.
Fixes #417

Pipeline ID can be passed into the executor

---

lib/cog/command/pipeline/executor.ex

Previously, we had a hard-coded initial context inside the Executor. For
pipelines triggered by external events, we'll need a mechanism by which
to seed that initial context with arbitrary data (e.g., webhook request
bodies).
This lays the groundwork for that: if a request comes in with a map or
list stored under the "initial_context" key, that will be used. If
nothing is explicitly set, the same initial context as before (namely,
an empty map) will be used. Thus, all chat-adapter initiated pipelines
will continue to behave as before.
Created `store_with_template/2` and `remove_template/1` helper functions
to better encapsulate some manipulation operations so they're more
obvious.
Fixes #418
Also adds a few Credo-related cleanups in the Executor.

Allow an initial context to be passed to Executor

---

lib/cog/command/pipeline/executor.ex
lib/cog/events/pipeline_event.ex

This will give a more complete picture of exactly what each command
invocation is operating on.
Example output taken from our test runs, formatted for readability
(notice that `multiple`-execution commands receive a single map, while
`once` commands receive a list):
```json
{
"data": {
"cog_env": {
"foo": {
"bar": {
"baz": "stuff"
}
}
},
"command_text": "operable:filter --path=foo.bar.baz --matches=me",
"relay": "396bf701-fef6-4628-a39b-22cf5c8cbfa5"
},
"elapsed_microseconds": 31390,
"event": "command_dispatched",
"pipeline_id": "8efa3ee7adec4af098e22bcb45667548",
"timestamp": "2016-03-22T01:01:38Z"
}
```
```json
{
"data": {
"cog_env": [
{
"command": "operable:rules",
"id": "9ec8b7a1-b00b-4166-9f99-444a3252b23a",
"rule": "when command is operable:rules must have operable:manage_commands" …
```

Add COG_ENV to pipeline "command_dispatched" events

---

lib/cog/command/pipeline/executor.ex
lib/cog/queries/user.ex

A recent refactoring around chat handle management inadvertently broke
the "user not found" functionality in the executor.
This commit uses the correct query name, and adds the chat handle
preload back to the query.

Fixes "user not found" functionality

---

test/integration/alias_execution_test.exs
test/integration/command_test.exs
test/integration/commands/alias_test.exs
test/integration/commands/table_test.exs
test/integration/commands/which_test.exs
test/integration/group_test.exs
test/integration/permission_test.exs
test/integration/role_test.exs
test/integration/sort_test.exs
test/support/adapter_case.ex

Adds an `assert_message/2` helper to the tests. Should make writing and modifying tests a bit easier.

add assert_message helper

---

lib/cog/bundle/install.ex
lib/cog/commands/filter.ex
lib/cog/commands/raw.ex
lib/cog/commands/sort.ex
lib/cog/commands/table.ex
lib/cog/commands/unique.ex
lib/cog/models/command.ex
priv/repo/migrations/20160325211544_drop_command_calling_convention.exs

Removes references to command calling convention.
partially resolves https://github.com/operable/cog/issues/421

remove calling convention

---

lib/cog/command/command_sup.ex
lib/cog/command/permissions_cache.ex
lib/cog/command/pipeline/executor.ex
lib/cog/command/user_permissions_cache.ex
lib/cog/commands/alias/ls.ex
lib/cog/commands/alias/mv.ex
lib/cog/commands/alias/new.ex
lib/cog/commands/alias/rm.ex
lib/cog/commands/helpers.ex
lib/cog/commands/permissions.ex
lib/cog/commands/which.ex
test/support/adapter_case.ex

We now lookup the user (from chat provider id) in the executor which is then passed on to the user permissions cache and further on to commands. All commands now pull user info out of the request struct they are given.
Closes https://github.com/operable/cog/issues/451

Include user in command request

---

lib/cog/command/pipeline/executor.ex
lib/cog/events/util.ex
test/integration/alias_execution_test.exs
test/integration/command_test.exs
test/integration/commands/alias_test.exs
test/integration/group_test.exs
test/integration/hipchat_test.exs
test/integration/permission_test.exs
test/integration/role_test.exs
test/integration/rule_test.exs
test/integration/slack_test.exs
test/support/adapter_assertions.ex
test/support/adapter_case.ex
test/support/adapters/hipchat/helpers.ex
test/support/adapters/slack/helpers.ex

Previously, error messages were generated in a number of places, making
it difficult to get a grasp on the variety of responses generated.
Additionally, error messages did not contain all that much context about
the error, something we'd need to address before allowing pipelines to
be triggered by external events.
Here, (almost) all error handling is consolidated into one place in the executor,
with lots of additional context added.
(Error messages for people lacking a Cog account, as well as for bad
redirects, are still handled as they were, since these were already
complex messages. Once we have error templates, everything will be able
to be consolidated even further.)
Tests have been updated, but in an admittedly less-than-satisfying
way. They are still strongly coupled to the exact …

Overhaul executor error-handling

---

test/controllers/v1/user_controller_test.exs
web/controllers/v1/user_controller.ex
web/views/user_view.ex

Adds the groups that a user is in when retrieving a user. Instead of using EctoJson, the User view is used for formatting the response.
Fixes https://github.com/operable/cog/issues/474

Add group memberships to users

---

lib/cog/commands/permissions.ex
lib/cog/models.ex
lib/cog/models/relay.ex
lib/cog/models/relay_group.ex
lib/cog/models/relay_group_membership.ex
lib/cog/queries/relay_group_queries.ex
lib/cog/queries/relay_queries.ex
lib/cog/support/model_utilities.ex
mix.exs
priv/repo/migrations/20160328115654_create_relays.exs
priv/repo/migrations/20160328121935_create_relay_groups.exs
test/controllers/v1/permission_controller_test.exs
test/controllers/v1/relay_controller_test.exs
test/controllers/v1/relay_group_controller_test.exs
test/controllers/v1/relay_group_membership_controller_test.exs
web/controllers/v1/group_membership_controller.ex
web/controllers/v1/relay_controller.ex
web/controllers/v1/relay_group_controller.ex
web/controllers/v1/relay_group_membership_controller.ex
web/router.ex
web/views/relay_group_view.ex
web/views/relay_view.ex

Adds REST API w/supporting data model and migrations to manage relays and relay groups. Also lays foundation for Relay 2.0 changes.
Fixes #403.

Relay management API

---

test/controllers/v1/group_controller_test.exs
test/controllers/v1/group_membership_controller_test.exs
web/controllers/v1/group_controller.ex
web/controllers/v1/group_membership_controller.ex
web/views/groups_view.ex
web/views/roles_view.ex

This PR adds roles to the groups#show and groups#index API calls and retrieves groups, roles and users in a single call. (Instead of also needing to make a call to the group membership API).
The structure returned looks like the following:
```
%{"id" => "some-id",
"name" => "some-group"
"members" => %{"groups" => [[%{"id" => "group-id",
"name" => "some-group-name"}],
"roles" => [[%{"id" => "role-id",
"name" => "some-rolename"}],
"users" => [%{"id" => "user-id",
"username" => "some-username",
"email_address" => "some-email_address",
"first_name" => "some-firstname",
"last_name" => "some-lastname"}]
}
}
```
Fixes https://github.com/operable/cog/issues/462

Add groups, users, and roles to group#index and #show

---

lib/cog/models.ex
lib/cog/models/bundle.ex
lib/cog/models/relay.ex
lib/cog/models/relay_group.ex
lib/cog/models/relay_group_assignment.ex
lib/cog/models/relay_group_membership.ex
lib/cog/queries/bundles.ex
lib/cog/queries/relay_group_queries.ex
lib/cog/queries/relay_queries.ex
lib/cog/queries/repo.ex
lib/cog/repo.ex
lib/cog/support/model_utilities.ex
priv/repo/migrations/20160329185210_add_bundle_relay_group_assignments.exs
test/controllers/v1/bundles_controller_test.exs
test/controllers/v1/relay_group_controller_test.exs
test/controllers/v1/relay_group_membership_controller_test.exs
test/support/database_test_setup.ex
web/controllers/v1/bundle_status_controller.ex
web/controllers/v1/bundles_controller.ex
web/controllers/v1/relay_controller.ex
web/controllers/v1/relay_group_controller.ex
web/controllers/v1/relay_group_membership_controller.ex
web/router.ex
web/views/bundles_view.ex
web/views/relay_group_view.ex
web/views/relay_view.ex

This PR allows bundles to be associated with a group of relays through a RelayGroupAssignment association. From a high level, this involves:
* Add RelayGroupAssignments association between Bundles and RelayGroups
* Update RelayGroupMembershipController to support memberships and assignments and update routes accordingly
* Add Bundles to RelayGroupController#show and RelayGroupController#index
* Update BundlesController to use Phoenix views for rendering JSON and include RelayGroups

allow bundles to be assigned to relay groups

---

test/controllers/v1/user_controller_test.exs
web/controllers/v1/user_controller.ex

Add a new plug in the UserController that determines if this is a self updating task or if the manage_user permission is needed. Perform authorization only is not self_updating.
Fixes https://github.com/operable/cog/issues/489

Allow a user to update their own user data with or without the manage_users permission

---

priv/repo/migrations/20160404135526_fetch_user_permissions_honors_roles.exs
test/cog/models/user_repo_test.exs

Previously, the `fetch_user_permissions` stored procedure returned
inconsistent results because it did not retrieve permissions a user had
by being in a group that had a role that had the permission.
Fixes #496

fetch_user_permissions honors group-granted roles

---

test/controllers/v1/group_membership_controller_test.exs
test/controllers/v1/permission_controller_test.exs
test/controllers/v1/permission_grant_controller_test.exs
test/controllers/v1/role_grant_controller_test.exs
web/controllers/v1/group_membership_controller.ex
web/controllers/v1/permission_grant_controller.ex
web/controllers/v1/role_grant_controller.ex
web/router.ex

This PR significantly simplifies the behavior of permission related APIs in Cog. In the simplified model, users acquire a permission by belonging to a group that has been granted a role that has been granted some permissions.
This will cause some breakage in `cogctl` and `cog-api-client` when it is merged until they are updated to address the changes. The required updates are very minor since these changes largely remove endpoints, with just one exception for managing users within groups.
- Permissions cannot be granted directly to users or groups. They are only granted to roles.
- Roles cannot be directly granted to users. They are only granted to groups.
- Groups cannot contain other groups. Only users can be members of a group.
- **Groups API**:
- (REMOVED) …

Simplify permission related APIs

---

lib/cog/models/relay.ex
priv/repo/migrations/20160328115654_create_relays.exs
test/controllers/v1/relay_controller_test.exs
web/views/relay_view.ex

This is a quick PR to change the desc field to description, so that it is consistent throughout.
Fixes https://github.com/operable/cog/issues/487

Rename Relay desc to description

---

lib/cog/queries/bundles.ex
test/controllers/v1/bundles_controller_test.exs
test/controllers/v1/relay_group_membership_controller_test.exs
test/controllers/v1/rule_controller_test.exs
web/controllers/v1/relay_group_membership_controller.ex
web/controllers/v1/rule_controller.ex
web/views/bundles_view.ex
web/views/relay_group_view.ex
web/views/relay_view.ex
web/views/rule_view.ex

* Updated `GET /v1/bundles` and `GET /v1/bundles/:id` to include rules under the commands for each returned bundle and added a test.
* Refactored the related views in order to have a single canonical view for each resource. Rather than embedding functions like `render_rules` in `Cog.V1.BundleView`, we call `render(rule, RuleView, "rule.json")`. Note: I only applied this refactoring to views that were directly related to this change, rather than making it more globally.

Include rules in bundles#show and bundles#index

---

test/controllers/v1/role_grant_controller_test.exs
web/controllers/v1/role_grant_controller.ex

This allows a group to be assigned a role. The namespace information in a permission was not being preloaded.

Fix granting a group a role

---

lib/cog/audit_message.ex
lib/cog/command/pipeline/executor.ex
lib/cog/error_response.ex
lib/cog/template.ex
priv/repo/migrations/20160406172300_insert_error_templates.exs

This provides only 2 basic error templates to start; an unregistered user template and a generic error template used from the `user_error` function. Also all custom messages for the generic errors and audit messages were pulled out into their own modules.
Closes https://github.com/operable/cog/issues/470

Error templates

---

lib/cog/bundle/embedded.ex
lib/cog/commands/group.ex
lib/cog/commands/permissions.ex
lib/cog/commands/role.ex
test/integration/group_test.exs
test/integration/permission_test.exs
test/integration/role_test.exs

Recently we simplified the authorization model. Now, groups may only
contain users, roles can only be granted to groups, and permissions may
only be assigned to roles.
Now, the embedded bundle commands conform to this; you can no longer add
groups to groups, grant permissions to users or groups, or grant roles
to users.
Permissions used by the commands were cleaned up, and authorization
rules were tightened up.
Fixes #512

Embedded commands conform to new authz model

---

lib/cog/models/bundle.ex
lib/cog/relay/relays.ex
priv/repo/migrations/20160411203730_add_version_to_bundles.exs
test/cog/command/command_resolver_test.exs
test/cog/models/bundle_test.exs
test/cog/models/command_test.exs
test/cog/queries/command_test.exs
test/cog/rule_test.exs
test/controllers/v1/bundles_controller_test.exs
test/support/database_test_setup.ex
web/controllers/v1/bundles_controller.ex

:warning: Based on https://github.com/operable/cog/pull/503
We're not currently handling multiple versions of bundles at the same time, but we are now keeping track of the version installed. If you try to install another version of a previously installed bundle, you'll receive an error.
Closes https://github.com/operable/cog/issues/98

Bundle versions are persisted when they are installed

---

lib/cog/relay/relays.ex
lib/cog/relay/tracker.ex

MQTT last will messages are apparently delivered even if a connection
fails authentication. This commit moves the log statement declaring Cog
has removed a dead Relay from its active list to the Relay.Tracker where
it's only logged if Cog knows the Relay.

Log relay removal only if Cog knows the relay

---

lib/cog.ex
lib/cog/bootstrap.ex
test/cog/bootstrap_test.exs
test/integration/group_test.exs
test/integration/role_test.exs
web/controllers/v1/bootstrap_controller.ex

**Updated bootstrap flow:**
* Create a new administrative user, using a parameter hash for the fields in the `%User{}` map, if present. If not, use the previous defaults.
* Create a `cog-admin` group and add the new administrative user to it.
* Create a `cog-admin` role, grant all of the `operable:*` permissions to it, and grant it to the `cog-admin` group.

make bootstrap group and role aware and allow custom user params

---

config/config.exs

This was leftover from the rename of "event hooks" to "triggers"

Rename a trigger-related environment variable

---

lib/cog/relay/relays.ex
lib/cog/relay/tracker.ex

This PR does a few things:
1. Prevents Cog from installing non-embedded bundles. Unknown bundles announced from external relays are treated as an error.
1. Removes the introduction step of the announcement waltz. This is no longer necessary.
1. Fixes a potentially misleading log message about relay removals.

Do not install non-embedded bundles

---

config/config.exs
test/controllers/v1/trigger_execution_controller_test.exs
web/controllers/v1/trigger_execution_controller.ex

Trigger timeouts are defined according to the needs of the
requestor (e.g. Github webhooks must respond within 30 seconds), which
includes network roundtrip time, as well as Cog's internal
processing. Cog itself can't wait that long to respond, as that'll be
guaranteed to exceed the HTTP requestor's timeout. As such, we'll bake
some slack into our internal timeout, allowing us to return to the
requestor within their timeout.
This can be configured on a system-wide basis.

Add some slack to trigger timeouts

---

lib/cog/models/group.ex
lib/cog/models/role.ex
priv/repo/migrations/20160415152542_protect_internal_rows.exs
test/cog/bootstrap_test.exs
test/cog/models/group_test.exs
test/cog/models/role_test.exs
web/controllers/v1/group_controller.ex
web/controllers/v1/role_controller.ex

* adds  constraint triggers to Postgres to prevent the cog-admin group and role and the operable bundle from being deleted or renamed.
* adds a changeset function to validate deletes of Group and Role models.
* updates changeset functions in Group and Role to reject name changes for the admin group and role
* updates the Group and Role API controllers to use the new changesets to validate deletes.
Note, this **does not** update the commands in the embedded bundle to use a changeset, so attempts to delete protected objects will result in a crash of the command when Postgrex raises an exception. These should be cleaned up in a future pull request.

prevent rename or delete of cog-admin group and role

---

lib/cog/relay/relays.ex

Prior order was reversed which resulted in setting state.tracker to `:ok `with obvious bad consequences.

Moved Logger call to before remove_relay/2 call

---

lib/cog/models/role.ex
priv/repo/migrations/20160419154716_protect_admin_role_permissions.exs
test/cog/models/role_test.exs

* adds a constraint trigger to prevent `operable:*` permissions from being revoked from the `cog-admin` role.
* with tests!
Note, there's some weirdness where testing the database constraint trigger. Ideally, `assert_raise` would be used here, but I couldn't figure out how to get it to work. Also, note that we can only test one permission in the test since the exception in Postgrex causes the transaction for the test to abort.

prevent embedded permissions in cog-admin role from being revoked

---

lib/cog/models/trigger.ex
priv/repo/migrations/20160418174310_triggers_enabled.exs
test/cog/models/trigger_test.exs
test/cog/repository/triggers_test.exs
test/controllers/v1/trigger_execution_controller_test.exs
test/views/trigger_view_test.exs
web/controllers/v1/trigger_execution_controller.ex
web/views/trigger_view.ex

Terminology change to bring it in line with how we talk about bundles,
which can also be active/enabled or inactive/disabled.

"Active" triggers are now "enabled"

---

test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex

This changes the expected json posted fora  bundle create to be:
```
{
"bundle": {
"config": ...config stuff...,
"enabled": true
}
}
```
where we used to only allow bundle config like:
```
{
"bundle": ...config stuff...
}
```
This allows us to easily set bundle attributes on create that aren't present in the config, which is used in https://github.com/operable/cogctl/pull/47

Apply bundle attributes that are not in config during creation

---

lib/cog/queries/bundles.ex
lib/cog/queries/command.ex
test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex
web/views/bundles_view.ex
web/views/commands_view.ex
web/views/rule_view.ex

This change adds permissions to the bundle under the command/rules path.
This PR also adds a CommandView for the command structure.
Fixes https://github.com/operable/cog/issues/540

Add permissions to bundles

---

lib/cog/models/relay.ex
test/controllers/v1/relay_controller_test.exs

Currently Relays require an ID to be set at startup time, but that ID is not known until after the Relay resource is created on Cog. This change allows the ID for a Relay to be included in the API call for the initial relay creation, which will make it easier for users to bootstrap an entire Cog cluster from scratch since a relay ID can be defined by the user in advance..
* Allow `POST /v1/relays` to include an ID. 
* Add tests to ensure that we don't allow the ID to be changed after create.

allow a relay to be created with a user-defined ID

---

config/config.exs
test/controllers/v1/trigger_execution_controller_test.exs
web/controllers/v1/trigger_execution_controller.ex

Noticed we still had an environment variable named `"SLACK"` and not
`"BUFFER"`. Also removed the `_sec` suffix.

Rename trigger_timeout_buffer config flag

---

lib/cog/queries/bundles.ex
test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex
web/views/bundles_view.ex

Include all the possible permissions in a bundle and not only the permissions used in the bundle rules.
Connected to https://github.com/operable/cog/issues/540

Include *all* permissions in a bundle

---

lib/cog/relay/relays.ex
lib/cog/relay/tracker.ex
lib/cog/repository/relays.ex
lib/cog/support/model_utilities.ex
test/controllers/v1/relay_controller_test.exs
test/support/database_test_setup.ex
test/support/fake_relay.ex
web/controllers/v1/relay_controller.ex

This adds a couple functions to the `Cog.Relay.Relays` module to enable and disable relays.

Adds support for enabling and Disabling relays

---

lib/cog/relay/info.ex

If a relay wasn't registered with Cog and it requested it's list of
bundles, Cog would try to return a payload of an empty list. This
would cause Carrier to crash. Now we just ignore messages from
unregistered relays.

Unregistered relays bug

---

config/config.exs

We received a report in public Slack that `cogctl chat-handles create` was failing without a timeout message. Upon further investigation, it turns out that the Slack API was taking more than 5 seconds to respond to the `users.list` API call -- in this case 9 seconds and the returned list was great than 5MB. Thanks @justinkinney for the great bug report and troubleshooting.
The path of least resistance here is to globally increase the HTTPotion timeout so we do that in `config/config.exs`.

Increase default HTTPotion timeout to 30 seconds (up from 5)

---

docker-compose-example.yml

This makes the docs easier to follow as you can copy and paste the following when creating a relay:
```
cogctl relays create default \
--token=$RELAY_COG_TOKEN \
--id=$RELAY_ID
```

Include relay env on cog container

---

lib/cog/bundle/embedded.ex

Prevents a non-obvious failure at startup if the database is slow to respond.

Wait until DB responds after processing bundle announcement

---

test/controllers/v1/user_controller_test.exs
web/controllers/v1/user_controller.ex

This adds a `/v1/users/me` route to return a standard user resource for the user associated with the token that was used to make the API call. This is helpful since the user may not know their UUID in advance, so it's difficult to make use of the existing `/v1/users/:id` route.

Add /v1/users/me route

---

scripts/docker-start

Rather than hard-coding localhost:5432, parse the DATABASE_URL
environment variable.

Parse database host from DATABASE_URL in docker-start

---

test/plugs/authorization_test.exs
web/controllers/v1/chat_handle_controller.ex
web/controllers/v1/user_controller.ex
web/plugs/authorization.ex

This commit moves the self updating check logic out of v1.UserController
and into Plug.Authorization where it can be more easily reused.
Fixes #596

Allow users to update  their own data.

---

web/controllers/v1/bundles_controller.ex

The message about the config file didn't make sense anymore, since you
can either send a file or pass the config directly.

Changed invalid config message to just "Invalid config."

---

lib/cog/command/service/memory.ex
lib/cog/command/service_sup.ex
test/cog/command/service/memory_test.exs

* Remonitor or delete related data for existing processes on init
* Periodically check all keys and remove anything that could have snuck in between process restarts

Deal with existing state when starting a memory service

---

test/support/adapter_case.ex
test/support/model_case.ex
test/test_helper.exs

Current Phoenix practice seems to be starting up a test transaction in
`test_helper.exs` and strategically rolling it back in specific test
cases as required.
The tests as they currently exist run fine, but in some I'm working on
in another branch, we can run into issues if we use our `ConnCase`
without also using our `ModelCase`, since the latter actually starts a
test transaction, but the former will roll one back.

Tweak transaction logic in tests

---

priv/repo/migrations/20160502183545_unique_handle_per_provider_per_user.exs
test/controllers/v1/chat_handle_controller_test.exs

Previously, a Cog user could actually have an unlimited number of chat
handles for a given provider (e.g., 5 different Slack handles mapping to
a single Cog user). This was an oversight that is now corrected.
There is already a unique constraint on `{provider_id, handle}`. By
replacing the constraint on `{user_id, provider_id, handle}` with the
simpler `{user_id, provider_id}`, we get the effect we want.
The controller tests were implicitly depending on the ability to
assign multiple handles to each user. They have been minimally
refactored to accommodate this index change, under the assumption that
they'll change more extensively with work for #604.

A user should have one chat handle per provider

---

lib/cog/command/service/memory.ex
lib/cog/command/service/pipeline_monitor.ex

I think this still logs all relevant info without making Cog logs too noisy. Since we log whenever a stale token is cleaned up we shouldn't lose any visibility.

Make dead token clean up less noisy

---

lib/cog/repository/chat_handles.ex
test/controllers/v1/chat_handle_controller_test.exs
web/controllers/v1/chat_handle_controller.ex
web/router.ex

Previously it was a bit awkward to know whether or not you needed to
create or update a chat handle for a user. It turns out we can simplify
things, because a user can only ever have a single chat handle for a
given chat provider. Whether the user already has a chat handle or not,
we can just say we're "setting" the chat handle and basically do an
"upsert" operation on the backend.
This removes the `PUT` operation on the chat handle controller. Now, to
both create and update a user's chat handle, send a `POST` to
`/v1/users/:id/chat_handles`.
This also puts a guard in against the situation where a user tries to
set a chat handle for a provider that differs from the
currently-configured Cog chat adapter. Previously, this would crash Cog;
now it's just an error tuple.
This also pulls this …

Chat handle creation is now an "upsert"

---

lib/cog/permissions/eval/conditional_expr.ex
lib/cog/rule_ingestion.ex
mix.exs
mix.lock

Commands can now define an open rule, `when command is bundle:command allow`. Commands with this rule may be executed by any registered user.
depends on https://github.com/operable/piper/pull/17

commands with the 'allow' rule can be ran by anyone

---

lib/cog/commands/alias.ex
lib/cog/commands/echo.ex
lib/cog/commands/filter.ex
lib/cog/commands/greet.ex
lib/cog/commands/help.ex
lib/cog/commands/max.ex
lib/cog/commands/min.ex
lib/cog/commands/raw.ex
lib/cog/commands/seed.ex
lib/cog/commands/sleep.ex
lib/cog/commands/sort.ex
lib/cog/commands/sum.ex
lib/cog/commands/table.ex
lib/cog/commands/thorn.ex
lib/cog/commands/unique.ex
lib/cog/commands/wc.ex
lib/cog/commands/which.ex

The removes references to enforcing commands and adds the rule `when command is operable:<command> allow` for all our internal commands.
reference #621

change 'enforcing: false' commands to 'allowed' commands

---

lib/cog/commands/alias.ex
lib/cog/commands/filter.ex
lib/cog/commands/group.ex
lib/cog/commands/help.ex
lib/cog/commands/max.ex
lib/cog/commands/min.ex
lib/cog/commands/permissions.ex
lib/cog/commands/raw.ex
lib/cog/commands/role.ex
lib/cog/commands/rules.ex
lib/cog/commands/seed.ex
lib/cog/commands/sleep.ex
lib/cog/commands/sort.ex
lib/cog/commands/sum.ex
lib/cog/commands/thorn.ex
lib/cog/commands/unique.ex
lib/cog/commands/wc.ex
lib/cog/commands/which.ex

Fixes indentation for markdown rendering and makes the headers and
formatting more consistent.

Clean up command documentation

---

mix.exs
mix.lock
test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex
web/views/bundles_view.ex

updates bundles controller to handle the new response signature of `Spanner.Config.validate`. Now if warnings are generated they are passed back to the user.
depends on https://github.com/operable/spanner/pull/70
reference https://github.com/operable/cog/issues/623

update bundles controller for config validator changes

---

lib/cog/queries/chat_handle.ex
test/controllers/v1/chat_handle_controller_test.exs
test/controllers/v1/user_controller_test.exs
test/integration/commands/relay_group_test.exs
web/controllers/v1/chat_handle_controller.ex
web/controllers/v1/user_controller.ex
web/views/chat_handle_view.ex
web/views/chat_provider_view.ex
web/views/user_view.ex

We needed a way for non-admin users to view their own chat handles. We
could have opened up chat_handle#index to the current_user, but I think
this is a more desirable option since it's a bit easier from an
implementation side in Cog, and it prevents having to make a second
request just to get the associated chat handle.

Nest chat_handles under users

---

lib/cog/adapters/slack/api.ex
lib/cog/adapters/slack/rtm_connector.ex
mix.exs
mix.lock

Closes #676 
We should also look into using the cached channels that the slack lib provides instead of keeping our own.

Expire channel in cache when channel events are received

---

lib/cog/commands/helpers.ex

Adds a simple usage macro. Using the macro adds a `help` option and a show_usage function.
Example:
```
Helpers.usage :root, """
USAGE
...
"""
```
You can also use without the `:root` bit. In that case it will add the show_usage function but won't add the help option. It's useful when your using it for subcommands.

Added usage macro

---

web/controllers/v1/group_controller.ex

If an unknown or bad id was passed to delete we would never render a response. Now we will.

Don't crash if an unknown id is passed to delete

---

lib/cog/commands/help.ex
lib/cog/models/bundle.ex
lib/cog/models/command.ex
lib/cog/queries/command.ex
lib/cog/templates/slack/help-command.mustache
lib/cog/templates/slack/help.mustache
test/integration/commands/help_test.exs

`help` now returns a list of commands or a single command when running `help` or `help <command>`. However, this does limit what we can print since templates are rendered per item in the list and not for the entire response. For instance description at the top of the old help output ("I know about these commands:") is no longer included in the output.
Also any errors encountered are returned as errors rather than returning a string of output.
Closes #672

Rework help command

---

config/config.exs
lib/cog/command/pipeline/executor.ex
lib/cog/service_endpoint.ex
web/views/service_view.ex
web/views/trigger_view.ex

This commit introduces two new environment variables which can be used
to override the base URLs for services and triggers:
$COG_TRIGGER_URL_BASE
$COG_SERVICE_URL_BASE
Setting either/both of these variables will override the base portion of the corresponding URL. This capability is useful when Cog is unable to detect the correct routable URL to send to clients. For example, firewalls and load balancers interpose themselves between clients and servers and require hosts behind them to carefully build any URLs returned in output so clients are able to access those resources.
Fixes #694

Override service and trigger base URLs

---

lib/cog/models/bundle_version.ex
lib/cog/repository/bundles.ex
test/cog/repository/bundles_test.exs
test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex

This prevents crashes when attempting to install the same bundle version
twice (as determined by bundle name and version string _only_; it
doesn't care if the contents of the bundle configuration file are
identical between versions).
We wrap all the bundle installation logic in a try/rescue block, and
trigger a transaction rollback if any `Ecto.InvalidChangesetError`s are
raised. Thus, this will actually protect against _any_ error raised in
the installation process.

Add uniqueness constraint to bundle version model

---

lib/cog/audit_message.ex
lib/cog/command/command_resolver.ex
lib/cog/command/option_interpreter.ex
lib/cog/command/permission_interpreter.ex
lib/cog/command/pipeline/executor.ex
lib/cog/command/pipeline/parser_meta.ex
lib/cog/command/pipeline/plan.ex
lib/cog/command/pipeline/planner.ex
lib/cog/error_response.ex
lib/cog/repository/bundles.ex
lib/cog/repository/rules.ex
test/cog/command/command_resolver_test.exs
test/cog/command/pipeline/binder_test.exs
test/cog/command/pipeline/planner_test.exs
test/support/executor_helpers.ex

Previously, during parsing, we would return a `CommandVersion` model
corresponding to the specific command details for the appropriate
enabled bundle; this "metadata" was then utilized in several places in
the pipeline execution flow. In particular, this is the mechanism by
which we retrieved the rules to evaluate to determine if a user was
authorized to execute a given command.
With the introduction of bundle versions, the association of
user-entered rules with the "site" bundle, and the internal
enabling/disabling of rules, retrieval of rules for a given command
became more complicated, particularly since such requirements cannot
currently be expressed as an Ecto association. A minimal solution would
be to retrieve the appropriate rules "out of band" and then replace the
"wrong" …

Formally define contract for parser metadata

---

lib/cog/repository/bundles.ex
lib/cog/repository/rules.ex
test/cog/repository/bundles_test.exs
test/controllers/v1/bundles_controller_test.exs

The easiest way to ensure that we fail the installation transaction is
if everything that could fail raises an exception of some kind. Many
functions already did that but weren't named with the `!` mnemonic;
those have been fixed to make reasoning about the code a bit easier.
Additionally (and crucially) failure of rule ingestion outside of a
transaction of its own will now raise a new `Cog.RuleIngestionError` if
anything fails. This then bubbles up to trigger transaction rollbacks as
appropriate.
Tests were added.

Ensure bundle installation is truly transactional

---

lib/cog/models/bundle.ex
lib/cog/protected_bundle_error.ex
lib/cog/repository/relay_groups.ex
test/controllers/v1/relay_group_membership_controller_test.exs
web/controllers/v1/relay_group_membership_controller.ex

We shouldn't be able to assign the `operable` or `site` bundles to a relay group. Assigning the latter should be harmless, though confusing; assigning the former would probably break everything, since it's an Elixir bundle and Relay doesn't know anything about those.

Do not assign special bundles to relay groups

---

lib/cog/models/types/version_triple.ex
test/cog/models/types/version_triple_test.exs
test/cog/repository/bundles_test.exs

Previously, we strictly required a String in `"major.minor.patch"`
format for a version. Now, we'll accept any of the following:
* major version, as integer
* major.minor version as float
* "major" version as string
* "major.minor" version as string
* "major.minor.patch" version as string (previous behavior)
That is, `1`, `1.0`, `"1"`, `"1.0"`, and `"1.0.0"` are all equivalent
now.

Be more accepting in what we consider a "version"

---

priv/repo/migrations/20160531183124_carry_over_enabled_bundle_state.exs

This will ensure that everything that was enabled in a 0.6.0 system
remains enabled in a 0.7.0 system. Relies on the old bundle data still
being around.

Migrate enabled bundle state from older installations

---

lib/cog/commands/help.ex
lib/cog/models/command_version.ex
lib/cog/repository/commands.ex

If you call help on a disabled command you will now receive the following:
```
Command "mist:ec2-find" is disabled. Run "bundle enable mist" to enable it.
```

Find enabled and disabled commands to print helpful error

---

test/controllers/v1/trigger_execution_controller_test.exs
web/controllers/v1/trigger_execution_controller.ex

This PR will allow triggers to accept and decode POST bodies that are encoded as `x-www-form-urlencoded` with the key/value pairs mapped to `cog_env.body` in the same was as JSON payloads. This allows triggers to serve as an endpoint for webhooks like Slack's slash commands that do not encode the body as JSON.
Simply sends the text after the slash command to @imbriaco via DM:
```
$ cogctl triggers create --name cog_register --pipeline 'echo $body.text > chat://@imbriaco' --as-user admin --enabled
ID              f9d362a5-910a-4941-bafb-3a277015bf6b
Name            cog_register
Pipeline        echo $body.text > chat://@imbriaco
Enabled         true
As User         admin
Timeout (sec)   30
Description
Invocation URL  http://localhost:4001/v1/triggers/f9d362a5-910a-4941-bafb-3a277015bf6b
``` …

Allow Triggers to receive x-www-form-urlencoded payloads as well as JSON

---

Dockerfile

- Updated image to use Alpine 3.4 
- Note: Gliderlabs images not yet available so we built our own from their tooling
- Use default Elixir and Erlang packages from Alpine

use alpine 3.4 and the default erlang/elixir

---

Dockerfile

This UID and GID are already being used by chance. Being explicit here prevents us from being surprised if they change in the future.

use predictable uid/gid for operable user to facilitate user namespacesa

---

lib/cog/models/user.ex
lib/cog/repository/groups.ex
priv/repo/migrations/20160617190613_protect_admin_group_membership.exs
web/controllers/v1/group_membership_controller.ex

We now protect the admin's membership to the cog-admin group via a db trigger. If deleted via the API we return a descriptive error message.
It turns out the admin user and cog-admin group are both already protected from name changes.

Protect admin group memberships

---

lib/cog/commands/bundle.ex
lib/cog/commands/bundle/disable.ex
lib/cog/commands/bundle/enable.ex
lib/cog/commands/bundle/info.ex
lib/cog/commands/bundle/list.ex
lib/cog/commands/bundle/versions.ex
lib/cog/repository/bundles.ex
lib/cog/templates/slack/bundle-info.mustache
lib/cog/templates/slack/bundle-list.mustache
lib/cog/templates/slack/bundle-versions.mustache
test/integration/commands/bundle_test.exs

for the most part, anyway... we're not dealing with bundle install /
uninstall from chat right now.
`list`, `info`, and `versions` subcommands were added, so we can now
see what's actually installed. The `status` command was removed, since
`info` does its job now.
Existing subcommands were refactored to the subcommand-per-module
pattern.
Fixes #776

Bring `operable:bundle` command to parity with cogctl

---

lib/cog/commands/user.ex
lib/cog/commands/user/info.ex
lib/cog/commands/user/list.ex
lib/cog/templates/slack/user-info.mustache
lib/cog/templates/slack/user-list.mustache

Currently provides `list` and `info` subcommands.
Fixes #147

Add an `operable:user` command

---

lib/cog/command/pipeline/executor.ex
lib/cog/relay/relays.ex
lib/cog/relay/tracker.ex

This commit modifies Cog.Command.Pipeline.Executor to remember and reuse the Relay chosen to run an invocation for a bundle version. The memory persists between plans and stages allowing Cog to take maximum advantage of Relay's container reuse for a given pipeline.
The Executor also performs a safety check when it uses a cached Relay assignment. Before executing `current_plan`, the Executor double checks the selected Relay is still valid for the bundle version. If the Relay assignment is invalid (Relay is offline or the bundle version has been disabled/uninstalled) the Executor will attempt to select another Relay once before giving up and returning an error to the user.
Fixes #777

Cache and reuse relay assignments

---

config/config.exs
lib/cog/adapters/hipchat/connection.ex
lib/cog/adapters/irc/connection.ex
lib/cog/adapters/slack/rtm_connector.ex
lib/cog/command/pipeline/executor.ex

* Allow command prefix to be configured via `$COG_COMMAND_PREFIX`
* `Regex.escape` the prefix when we strip it from spoken commands

Improve command prefix handling

---

test/controllers/v1/chat_handle_controller_test.exs
test/plugs/authorization_test.exs
web/controllers/v1/chat_handle_controller.ex
web/controllers/v1/user_controller.ex
web/plugs/authorization.ex

Since allow_self_updates was hardcoded to only work with :update and :show, chat_handle :upserts would fail if the user didn't have the `manage_users` permission. This fixes the problem by allowing a list of actions to be passed to `allow_self_updates`. We also now have a test to make sure that even users without `mange_users` permission can update their own chat_handle.
This partially resolves https://github.com/operable/flywheel/issues/362

allow self updates takes a list of actions

---

lib/cog.ex
lib/cog/bootstrap.ex

Create an administrative user using values from the environment, if present. If any of the following variables are not set, the bootstrap will not be performed. Required variables:
```
COG_BOOTSTRAP_USERNAME
COG_BOOTSTRAP_PASSWORD
COG_BOOTSTRAP_EMAIL_ADDRESS
COG_BOOTSTRAP_FIRST_NAME
COG_BOOTSTRAP_LAST_NAME
```
Additionally, if the user bootstrap completes successfully and the `RELAY_ID` and `RELAY_COG_TOKEN` variables are set, a relay will be created using the variables and assigned to a default relay group, which will also be created.  If the relevant variables are not present, this step will be skipped.
If any creation attempt fails, the entire bootstrap process will be rolled back.

Automatically bootstrap using environment variables, if present.

---

lib/cog/repository/bundles.ex
lib/cog/support/model_utilities.ex
test/cog/repository/bundles_test.exs
test/controllers/v1/rule_controller_test.exs
test/integration/commands/help_test.exs
test/integration/commands/rule_test.exs

To avoid confusion between "official" Operable-authored bundles and 3rd
party bundles, we'll block the installation of bundles named
* `cog`
* `cog-*`
* `operable-*`
The bundle names `site` and `user` continue to be reserved for internal
usage. The embedded bundle continues to be named "operable", and
continues to be uninstallable by outside sources.
We were using "cog" as a bundle name for testing data; obviously that's
out now, so we'll now call it "test-bundle" instead.
Fixes #817

Squat on certain bundle names

---

lib/cog/commands/alias.ex
lib/cog/commands/bundle.ex
lib/cog/commands/group.ex
lib/cog/commands/relay.ex
lib/cog/commands/relay_group.ex
lib/cog/commands/rule.ex
lib/cog/commands/trigger.ex
lib/cog/commands/user.ex
test/integration/commands/bundle_test.exs
test/integration/commands/group_test.exs
test/integration/commands/relay_group_test.exs
test/integration/commands/relay_test.exs
test/integration/commands/role_test.exs
test/integration/commands/rule_test.exs
test/integration/commands/trigger_test.exs
test/integration/commands/user_test.exs

Previously, a few commands would actually display an error message,
but not create a formal error, which would allow a pipeline to
continue.
Now, each command behaves similarly, and appropriately.

Unrecognized subcommands are failures

---

lib/cog/repository/bundles.ex

Many of our templates have a trailing newline that is helpfully added by our editors which is causing template output to be unnecessarily double spaced. This PR will remove a single newline from the end of the template body.
Note that this intentionally only removes _one_ trailing newline to allow users to include empty lines at the end of their template intentionally if they want.

remove one empty line from the end of the template body if present

---

lib/cog/audit_message.ex

This fixes a source of frequent audit logger crashes.

Fixes crash in AuditMessage.render()

---

config/config.exs
lib/cog/log_helper.ex

Disable Ecto query logging "noise" since almost (all?) of the output isn't helpful.
Lines logged during startup:
Before: 1552
After: 115
Fixes #841

Disable Ecto query logging

---

mix.lock

See also
* https://github.com/operable/spanner/pull/73
* https://github.com/operable/go-relay/pull/31
* https://github.com/operable/circuit/pull/1
Fixes #838

Bump spanner to pick up changes for docker bind mounts

---

lib/cog/relay/info.ex

Typo caused Cog to crash when calculating dynamic config
signatures. Since it would recover quickly the crash would give the
appearance of Relay hanging.
Fixes #861

bundle.name -> bundle_name

---

config/embedded_bundle_version.exs
lib/mix/tasks/cog.embedded.ex

TL;DR - checksums can change with different MIX_ENV, a detail that is
irrelevant for our purposes. Read the code comments for details.
Also changes the stored checksum for the embedded bundle; the old value
was actually computed under MIX_ENV=test. This change returns it to the
MIX_ENV=dev checksum that it originally was (but the version will stay
the same, because that's how this stuff works....)

Only checksum embedded bundle when MIX_ENV=dev

---

lib/cog/models/bundle_dynamic_config.ex
lib/cog/relay/info.ex
lib/cog/repository/bundles.ex
priv/repo/migrations/20160725170913_layered_dynamic_config.exs
test/controllers/v1/dynamic_config_controller_test.exs
web/controllers/v1/bundle_dynamic_config_controller.ex
web/router.ex
web/views/bundle_dynamic_config_view.ex

Adds the ability to manage "layers" of dynamic bundle configuration. The
previous notion of dynamic configuration is referred to now as the
"base" layer, but now we may add "room" and "user" layers on top. Relay
can apply these in order to override the base layer depending on which
user issues a command, and from which room it is issued.
Layers can have names, indicating which user or room they apply to. The
base layer is always named "config" by convention (it could be named
anything, really).
There can only be one base layer per bundle, but multiple room and user
layers, provided they each have a different name.
A REST API is provided to manipulate each layer of a bundle
individually. Additionally, all layers for a bundle may be retrieved at
once.
Cog now returns all layers for all …

Support layered dynamic bundle configuration

---

DEVELOP.md

Prior to this commit the enumerated requirement was simply `Postgres`; however,
`priv/repo/migrations/20160524190528_parse_tree_is_json.exs` attempts to use
the `jsonb` type, which is not available until Postgres 9.4 and later.

update version requirement for Postgres

---

lib/cog.ex
lib/cog/bus_driver.ex
lib/cog/core_sup.ex

- `Cog.BusDriver` now traps exits if it successfully starts
`emqttd`. This allows Cog to keep the message bus state in sync with
Cog's overall state. If Cog is up, the message bus is up. If Cog is
down, the message bus is down.
- Removed the `mnesia` data file deletion logic from
`Cog.BusDriver. Wound up causing more problems than it solved. We can
tell users to delete the data dir in the release notes.
- Moved all of Cog core, modulo `Cog.Repo` and `Cog.BusDriver`, to a
separate supervisor named `Cog.CoreSup` with a restart strategy of
one-for-one. The top level supervisor is now responsible for
`Cog.Repo`, `Cog.BusDriver`, and `Cog.CoreSup` and uses the
one-for-all restart strategy. This should stabilize Cog as all
processes will be restarted if the database or message bus goes down. …

Fix emqttd mgmt;Refine process tree structure

---

config/config.exs
config/dev.exs
config/test.exs
lib/cog/email.ex
lib/cog/models.ex
lib/cog/models/password_reset.ex
lib/cog/repository/users.ex
mix.exs
priv/repo/migrations/20160803163007_password_reset.exs
priv/repo/migrations/20160803165909_add_unique_constraint_to_users_email_address.exs
test/controllers/v1/password_reset_controller_test.exs
test/emails/password_reset_test.exs
web/controllers/v1/password_reset_controller.ex
web/router.ex
web/templates/email/reset_password.text.eex
web/views/email_view.ex

Adds two endpoint to Cog for resetting passwords, `POST /v1/users/reset-password` and `PUT /v1/users/reset-password/:id`.
In order to work Cog needs to be able to send emails. Email is sent via SMTP and is configured with the following env vars:
- `COG_SMTP_SERVER`
- `COG_SMTP_PORT`
- `COG_SMTP_USERNAME`
- `COG_SMTP_PASSWORD`
- `COG_SMTP_SSL` (default: false)
- `COG_SMTP_RETRIES` (default: 1)
Additionally there are a couple other env vars used to configure Cog for password resets:
- `COG_EMAIL_FROM` - The email address from which Cog will send emails.
- `COG_PASSWORD_RESET_BASE_URL` - This is the base url Cog will use as the password reset link in password reset request emails. The reset url is build by appending `?token=<token>` as a query param to the base url.
resolves #894

reset password endpoints

---

.dockerignore
scripts/docker-build

Previously, if you didn't edit the `scripts/docker-build` file
beforehand, you could build an image that had the "wrong" version of
`cogctl` included. This version would always be build from `master` of
`cogctl`, and not necessarily the version that corresponded with the
`cog` you were building.
Now, the script figures out what branch `cog` is checked out to, and if
`cogctl` has a branch of the same name, it will check `cogctl` out on
that branch. If it doesn't, then it will fall back to the `master`
branch in `cogctl`.
Previously, we had `.git` in our `.dockerignore` file, but that would
make it impossible to determine `cog`'s current branch. Now, we don't
ignore `.git`, but we do remove it from the image before we finish
building. We also do the same for `cogctl` (which we weren't …

Sync cogctl and cog in the Docker image

---

lib/cog/command/pipeline/destination.ex
lib/cog/command/pipeline/executor.ex
lib/cog/command/pipeline/initializer.ex
lib/cog/command/reply_helper.ex
lib/cog/commands/user/attach_handle.ex
lib/cog/commands/user/detach_handle.ex
lib/cog/commands/user/list_handles.ex
lib/cog/messages.ex
lib/cog/support/model_utilities.ex
test/cog/command/pipeline/destination_test.exs
test/integration/slack_registration_test.exs
test/integration/slack_test.exs
test/support/adapters/slack/helpers.ex

There were a handful of places where we were still treating chat rooms and users as plain maps, rather than Conduit-enabled structs, which would cause failures when we tried interacting with them in terms of the `Access` protocol, which structs do not implement by default.
This should flush out all those last remaining calls, as well as finishes the transition to completely validated messages, by ensuring that `Cog.Chat.User` and `Cog.Chat.Room` are used everywhere.
Additionally, tests were added around the autoregistration functionality, which is where this problem surfaced.

Fix access errors

---

lib/cog/command/option_interpreter.ex
test/cog/command/option_interpreter_test.exs

Allows list-valued options to be specified one-value-at-a-time:
do:something --foo=one --foo=two --foo=three
In service of #919

List-valued Options

---

config/config.exs
config/dev.exs
config/prod.exs
config/test.exs
lib/cog/chat/adapter.ex
lib/cog/chat/http/connector.ex
lib/cog/chat/http/provider.ex
lib/cog/chat/http/supervisor.ex
lib/cog/chat/slack/connector.ex
lib/cog/chat/slack/formatter.ex
lib/cog/chat/slack/provider.ex
lib/cog/core_sup.ex
test/support/adapter_case.ex
test/support/adapters/test/helpers.ex
test/support/test_provider.ex
web/controllers/v1/trigger_execution_controller.ex

Instead of tossing all the provider implementation code in a single
directory, consolidate by implementation; all Slack-related code goes in
`lib/cog/chat/slack`, HTTP-related code goes in `lib/cog/chat/http`,
etc.
This will make it easier to manage as we add more implementations, and
more features per implementation.

Organize provider code by implementation

---

config/config.exs

Adds a `COG_DB_SSL` environment variable that allows SSL support for Postgres to be enabled.

Allow Postgres SSL connections

---

lib/cog/commands/help/command_formatter.ex
lib/cog/models/command_opt.ex
priv/repo/migrations/20160909200244_rename_command_option_desc_to_description.exs

* Fixes missing command option description
* Condenses options to a single segment of the synopsis once there are more than 5

Help docs improvements

---

lib/cog/commands/help/command_formatter.ex

Renders short flags like the following:
```
OPTIONS
-a <app>, --app <app>
App for which to read the config
-v, --verbose
Print extra details
```

Render short flag when set

---

lib/cog/repository/bundles.ex

Fixes @imbriaco's issue:
```
imbriaco [10:53 AM]  
@ash help
ashBOT [10:53 AM]  
ENABLED BUNDLES
* cfn - AWS CloudFormation
* operable - Core chat commands for Cog
DISABLED BUNDLES
* cfn - AWS CloudFormation
To learn more about a specific bundle and the commands available within it,
you can use `operable:help <bundle>`.
imbriaco [10:54 AM]  
@vanstee ^^^ note the `cfn` bundle duplicated.
[10:54]  
Guessing that's because of multiple versions.
```

Only return disabled bundles from disabled bundle query

---

priv/templates/common/text.greenbar

Discovered this while writing a command that wrapped an existing,
non-Cog aware executable. The output was just what the wrapped program
returned on standard output. Without this fix, only the first line of
that output showed up in chat. Now, everything comes through.

Actually print all lines of text output

---

lib/cog/commands/relay/list.ex
lib/cog/commands/relay/update.ex
lib/cog/commands/relay_group.ex
lib/cog/commands/relay_group/create.ex
lib/cog/commands/relay_group/delete.ex
lib/cog/commands/relay_group/info.ex
lib/cog/commands/relay_group/list.ex
lib/cog/commands/relay_group/member.ex
lib/cog/commands/relay_group/member/add.ex
lib/cog/commands/relay_group/member/assign.ex
lib/cog/commands/relay_group/member/remove.ex
lib/cog/commands/relay_group/member/unassign.ex
lib/cog/commands/relay_group/rename.ex

A few commands weren't using the `Helpers.usage` macro that everything
else was using.

Send relay, relay-group usage messages to template

---

lib/cog/chat/slack/connector.ex
test/integration/slack_test.exs
test/support/adapters/slack/helpers.ex

This allows the bot to both communicate and redirect messages to private channels (also known as groups in the API). Redirection also has some bugs, so I held off from writing a test for that until we rework that.
Fixes https://github.com/operable/cog/issues/973

Support slack private channels (groups)

---

config/config.exs
lib/cog.ex
lib/cog/command/pipeline/planner.ex

_Caveat: I'm conflicted on whether or not this is a good idea. Feedback encouraged!_
This PR introduces a new config entry, `:access_rules` which controls whether or not Cog enforces access rules associated with command invocations. Setting this entry to `:enforcing` causes Cog to enforce access rules just as it currently does. `:enforcing` is also the default.
Setting the entry to `:unenforcing` disables access rule enforcement **globally** for the entire Cog installation. This is intended to simplify Cog adoption for teams which have previous experience with simpler bots such as Hubot and Lita. Later, they can set `:access_rules` to `:enforcing` and take advantage of Cog's access controls.
Disabling access rule enforcement causes Cog to log an explicit warning at startup. Values other …

Add global switch to toggle access rule enforcment

---

lib/cog/chat/slack/connector.ex

This commit changes the Slack provider to treat messages with either the `is_bot` flag set OR user.name == `slackbot` as coming from a bot user. This is an important distinction to make as these classes of messages have different fields. Using the wrong one can result in a process crash when a non-existent field is referenced.
The fix is based on inspection of strack traces from Cog instances encountering this problem on Slack. I haven't been able to figure out how to get Slack to generate these slackbot messages myself hence no additional tests.
This commit also fixes some wonky first_name, last_name handling behavior introduced in an earlier commit.
Fixes #982

Don't crash on slackbot messages

---

lib/cog/chat/slack/template_processor.ex

Slack uses `•` rather than `*` to denote a bullet.

Fix slack bullets

---

lib/cog/chat/adapter.ex
lib/cog/chat/provider.ex
lib/cog/chat/slack/connector.ex
lib/cog/chat/slack/provider.ex
lib/cog/command/pipeline/destination.ex
test/integration/slack_test.exs
test/support/adapters/slack/helpers.ex
test/support/test_provider.ex

This changes the `Cog.Chat.Adapter.lookup_room` function to take a keyword list as it's second argument containing either `[id: id]` or `[name: name]`. Making the call more explicit should help simplify the lookup room logic in the adapter.
resolves #976 
TODO:

Lookup room refactor

---

lib/cog/bundle_registry.ex
lib/cog/commands/bundle.ex
lib/cog/commands/bundle/install.ex
priv/templates/embedded/bundle-install.greenbar
test/cog/chat/slack/templates/embedded/bundle_install_test.exs
test/integration/commands/bundle_test.exs

This adds support for installing a bundle via the registry.
Example:
```
@vanstee: !bundle install heroku
@cog: Bundle "heroku" version "0.0.4" installed.
@vanstee: !bundle install pagerduty 0.0.1
@cog: Bundle "pagerduty" version "0.0.1" installed.
```
I'll follow this up with a `bundle uninstall` subcommand as well.

Bundle install via registry

---

lib/cog/commands/echo.ex
test/integration/commands/echo_test.exs

echo was causing Cog to crash whenever it received a value that didn't implement `to_string`, ie maps and lists. This change serializes those types with `Poison.encode!`.
resolves #981

serialize maps and lists when passed to echo

---

lib/cog/repository/bundles.ex

Not really sure how this ever worked, but I noticed that bundle description and long_description attributes weren't being pulled in during install.

Make sure we pull in the description and long_description

---

lib/cog/repository/bundles.ex
test/cog/repository/bundles_test.exs
test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex

Was having a hard time explaining what I was thinking so I thought I would just do it. This adds an extra config that causes bundle installation to overwrite the existing version if it already exists.
resolves #969

update bundles in place when in dev mode

---

lib/cog/chat/slack/provider.ex
test/integration/slack_registration_test.exs
test/integration/slack_test.exs
test/support/adapters/slack/helpers.ex

Returning the slack id of the user instead of the handle causes Slack to treat the output more predictably. Characters around the mention name don't cause Slack to not recognize the user's handle.
resolves #944 
TODO:

use the slack id for the mention name instead of the user handle

---

mix.lock
priv/templates/embedded/help-bundle.greenbar
test/cog/chat/slack/templates/embedded/help_bundle_test.exs

This adds an optional config section to the help output for bundles. The section contains notes and a list of env vars. Both notes and env vars are optional.
Note that I didn't add the config section info to the bundle version model. I'm just pulling straight from the config file in the template. Since the data was already available in the config file and it's not used anywhere else right now, I figured that was the easiest solution.
Example config.yaml excert:
```
...
config:
notes:
The cfn bundle makes use of CloudFormation stack templates and stack policies that are
defined in JSON documents and stored in pre-defined S3 locations. These locations are
defined with the 'CFN_TEMPLATE_URL' and 'CFN_POLICY_URL' configuration variables.
env:
- var: AWS_REGION
- var: AWS_ACCESS_KEY_ID
- var: …
```

Adds an optional config section to the help ouput for bundles

---

scripts/install_cog.ps1

The script would prompt the user for all required inputs, then it would
do all the steps mentioned in the installation guide automatically.

Add PowerShell script to simplify example setup process on Windows

---

config/helpers.exs

We crash naturally in `Cog.Chat.Adapter` if there are no providers, so I just return nil if one isn't specified. I'm still raising in the config when a user specifies multiple chat adapters. I think that is still ok, and we don't have add checking logic to the adapter.

don't raise in config when no provider is specified

---

lib/cog/chat/hipchat/util.ex
test/support/hipchat_client.ex

We weren't parsing out the jid from the stanza from attribute (ex: `479543_3152608@chat.hipchat.com/web||proxy|proxy-c410.hipchat.com|5252`) which resulted in us not being able to find the user in our local user cache so we ignored the message. Was a simple fix to parse out the jid.
Fixes #1053

Allow the bot to respond in HipChat DMs

---

lib/carrier/messaging/connection.ex
lib/cog.ex
lib/cog/bus_enforcer.ex
lib/cog/util/misc.ex
priv/config/ssl_mqtt.exs

Previously, only connections coming from Relays had usernames and
passwords associated with them; any connection from Cog itself had
neither. We would distinguish between them by examining which host the
connection was coming from; if it was 127.0.0.1, we treated it like it
was a Cog connection, and like a Relay connection (which needed to be
authenticated) otherwise.
This would cause Cog to crash if a Relay process was running on the same
host as Cog, and if it tried to connect prior to being registered with
Cog.
Now, _all_ connections have a username and password associated with
them. All Cog-initiated connections have a username of `COG_INTERNAL`,
and use a randomly-generated password that is generated at Cog startup,
allowing us to properly distinguish between Cog connections and …

All MQTT connections have usernames and passwords

---

lib/cog/chat/slack/connector.ex
lib/cog/chat/slack/provider.ex

If a slack user wasn't found we returned `nil` instead of an `{:error, :not_found}` tuple. This caused Cog to crash when calling `User.from_map/1` in `Cog.Chat.Adapter`. HipChat already returns a tuple so everything is groovy there.
resolves #1049

return an error tuple instead of nil when a slack user isn't found

---

config/config.exs

We should have bumped this back when we released Cog 0.14.0 (new
Greenbar templates).
Fixes #1063

Bump embedded bundle version to 0.14.0

---

lib/cog/bus_enforcer.ex

Added supported for "namespaced" relay ids

---

lib/cog/commands/raw.ex
priv/templates/embedded/raw.greenbar
test/cog/chat/hipchat/templates/embedded/raw_test.exs
test/cog/chat/slack/templates/embedded/raw_test.exs

The `raw` command simply takes whatever it gets on std and passes it along, basically stripping the template from the command output. We then take advantage of Cog's default behavior when there is no specified template, and just render the raw json. However, some commands just render text. We determine whether to render json or plain text based on the presence of a "body" key in the response. If a user pipes output from a command that returns text to raw, the object goes through unchanged and the output is rendered as text instead of as the raw json as expected.
To alleviate that we just copy the raw template to embedded and explicitly pass it in the return from the raw command.
resolves #1023

explicitly pass the 'raw' template for the 'raw' command

---

lib/cog/permissions/eval/contain_expr.ex
test/cog/permissions/eval_test.exs

Previously, the rule evaluator would coerce list type options into a string before evaluating the comparisons contained within the right-hand-side of an `in` operation. For example:
**String Comparison:**
Example Command:  `my-command --list foo --list bar --list baz`
Rule: `when command is my-command with option[list] in [ foo ] allow`
Evaluates: `"foobarbaz" == "foo"`
This would only return the expected result if the list option only had a single value.
**Regex Match:**
Example Command:  `my-command --list foo --list bar --list baz`
Rule: `when command is my-command with option[list] in [ /foo/ ] allow`
Evaluates: `Regex.match?(~r/foo/, "foobarbaz")`
The Regex version of this would usually return the expected results, though there could be unexpected behavior which would also affect the …

Fix rule evaluation for list options

---

config/test.exs
lib/cog/token_reaper.ex

The startup delay on the token reaper was causing the occasional db ownership error because it would try to query the db after we set `Ecto.Adapter.Sandbox.mode` to manual but before we update it to shared before tests. The db ownership error caused the token reaper to crash and then restart only to crash again. This created some pretty unstable and unpredictable test results.
By reaping tokens during init we hit the db before setting the sandbox mode to manual so the reaper doesn't start flopping. We do occasionally get db connection timeouts because the token reaper process hangs on to the connection for too long, but this doesn't cause the same instability that crashing the process does. I increased the ownership timeout to alleviate that a bit.
This isn't a 100% fix, but it does ease …

Remove token reaper startup delay and increase ownership timeout

---

.buildkite/pipeline.yml
Dockerfile.ci
Makefile
docker-compose.ci.yml
test/support/snoop.ex

This updates Cog tests to run in a docker container in CI. Ideally I think we would want to run integration tests in a separate step from unit tests, then we could parallelize unit tests across builds, but right now that requires us to build Cog twice and it takes forever. Probably a good use case for leveraging artifacts, but I didn't want to complicate this for now.
resolves #1072

Dockerized CI

---

lib/cog/command/option_interpreter.ex
test/cog/command/option_interpreter_test.exs

This PR fixes Cog's evaluation of required options.
Prior to this fix the `required_set` of options Cog used to check a given invocation would contain duplicate entries for required options which also defined a short flag. This caused false negatives unless the user specified the option twice.
Fixes #1088

Dedupe required option names before checking presence

---

.buildkite/pipeline.yml
.buildkite/scripts/trigger_dependent_build.sh

This is now a pipeline step, rathe than a post-command callback, in
order to ensure that it fires only after all preceeding steps pass.
For now, we're not requiring the cogctl pipeline to pass in order for
this cog pipeline to pass, but that can easily be added with a
subsequent API polling step in the future.

Trigger cogctl pipeline

---

config/config.exs
lib/cog/command/gen_command/base.ex
lib/cog/command/service/data_store.ex
lib/cog/command/service_sup.ex
lib/cog/commands/cat.ex
lib/cog/commands/tee.ex
lib/cog/nested_file.ex
test/cog/command/service/data_store_test.exs
test/cog/gen_command_test.exs
test/cog/nested_file_test.exs
test/commands/cat_tee_test.exs

* Creates a `DataStore` service based heavily on the `Memory` service, but which writes files to disk.
* This service is not exposed via the web API and is only currently intended for use by Cog internals.
* Data is written by default to a `service_data` directory under the top-level Cog `data` directory. This is configurable in `config.exs`.
* File manipulation is handled by a new `NestedFile` module which creates a multi-level directory hierarchy in order to reduce number of files which will be written to a directory for performance reasons.
* Adds a `tee` command to save pipeline output using the DataStore service for later use
* Adds a `cat` command to retrieve saved pipeline output
* Includes support for modifying the saved `tee` data with the current pipeline output in the following …

Adds tee and cat commands and a supporting DataStore service

---

config/config.exs
lib/cog/telemetry.ex

This adds an `env` key to the Cog start telemetry event with the value of `Atom.to_string(Mix.env)` so we can differentiate between `dev` instances, `test` instances, and `prod` instances.

add the env to the telemetry data

---

mix.lock

We just updated the yaml_elixir dependency, and wanted to make sure
this was up-to-date as well.

Update spanner dependency

---

lib/cog/audit_message.ex
lib/cog/command/command_resolver.ex
lib/cog/command/pipeline/executor.ex
lib/cog/error_response.ex
lib/cog/relay/relays.ex
lib/cog/relay/tracker.ex
lib/cog/repository/bundles.ex
mix.lock
test/cog/relay/tracker_test.exs

This adds/updates a number of error messages to make it easier for users to troubleshoot issues.
resolves #1092 
- Executing a command in a bundle not assigned to a relay group
- `Bundle 'test' is not assigned to a relay group. Assign the bundle to a relay group and try again.`
- Executing a command that only exists on a disabled relay
- `No Cog Relays supporting the`test`bundle are currently available. There are one or more relays serving the bundle, but they are disabled. Enable an appropriate relay and try again.`
- Updates to the standard "No Cog Relays supporting..." error
- `No Cog Relays supporting the`test`bundle are currently online. If you just assigned the bundle to a relay group you will need to wait for the relay refresh interval to pick up the new bundle.`
Provided by piper: …

error messages

---

config/config.exs
config/helpers.exs

The SMTP port was not being cast from the string we get from the environment to an integer.

Fix password reset email

---

lib/cog/commands/seed.ex
test/commands/seed_test.exs

This one is small but I broke it out because it changed the module name of the seed command and will require you to reset your test db before it will work.
part of #1122

Seed test update

---

lib/cog/commands/alias/create.ex
lib/cog/support/model_utilities.ex
test/cog/command/command_resolver_test.exs
test/commands/alias_test.exs
test/commands/which_test.exs

Reworks `alias` command tests. This also includes work to the `which` command tests since they are tied closely to aliases.
part of #1122

Alias test rework

---

lib/cog/commands/help.ex
lib/cog/repository/commands.ex
lib/cog/support/model_utilities.ex
test/commands/help_test.exs

Adds support for passing just the command name without the bundle and improves error messaging a bit.
resolves #1109

help no longer requires the fully qualified command name

---

lib/cog/commands/helpers.ex

`Cog.Repository.Commands.with_status_by_any_name/1` was returning a list but `Cog.CommandVersionHelpView.render/2` expected a single version. That was causing commands that use the `-h` flag to crash.
For now I'm just matching on a one item list because that's all that we should ever get in this particular case. But we should probably soon drop the special handling of help in embedded commands and start leveraging git style subcommands and the help command.
resolves #1154

fix embedded command -h flag

---

lib/cog/command/command_resolver.ex
mix.lock
test/cog/command/command_resolver_test.exs

Adds a new error when the specified bundle can't be found.
resolves #1155 
depends on https://github.com/operable/piper/pull/37

bundle not found error

---

lib/cog/commands/seed.ex
test/commands/seed_test.exs

While it is true that this module really should be renamed
`Cog.Commands.Seed` (note plural), it requires a bump to the embedded
bundle version; otherwise existing installations will be unable to
start.
While we could bump the version, it's better to roll back this change,
reserving version bumps for more meaningful changes.
(Incidentally, the `Cog.Command.Raw` module also needs changing in this
same way. Something for the future.)
For reference, this commit reverts
d6a22b6aabb2913931ff4477e5e515eca6bf2107, as well as part of
abd259a3ea6ef2e7da37bf11ab8510f693c92c82.
Fixes #1169

Rename back to Cog.Command.Seed

---

lib/cog/bootstrap.ex

When setting up a Cog system for the first time using `COG_BOOTSTRAP_*`
variables, a `COG_BOOTSTRAP_CHAT_HANDLE` variable may optionally be
set. The bootstrapping process will attempt to resolve this handle
according to the currently-active chat provider (controlled by
`COG_SLACK_ENABLED` and `COG_HIPCHAT_ENABLED`).
If the given handle is valid, it is associated with the bootstrapped
user. That user can immediately begin interacting with Cog via chat.
If the chat handle is not valid, a warning message is logged, but the
bootstrapped user is still created and the system still starts up as
usual. In this case, the user can use `cogctl` to set up a chat handle.

Optionally add chat handle for bootstrap user

---

config/config.exs
lib/cog/template/new/evaluator.ex
test/cog/template/new/evaluator_test.exs

The common error template is now configurable via the env var `COG_CUSTOM_TEMPLATE_DIR`. The var should point to a directory that contains a file named `error.greenbar` that will replace the standard `error.greenbar`.
I went the directory route so we can make additional templates configurable more easily in the future. Common templates that are configurable are white listed. Currently the only configurable template is the standard error template.
Documentation to come.
part of #1142

Make common error template configurable

---

config/config.exs
config/dev.exs
config/prod.exs
config/staging.exs
config/test.exs
lib/carrier/messaging/connection.ex
lib/carrier/messaging/gen_mqtt.ex
lib/cog/bundle/embedded.ex
lib/cog/chat/http/connector.ex
lib/cog/command/pipeline/destination.ex
lib/cog/command/pipeline/executor.ex
lib/cog/relay/info.ex
lib/cog/relay/relays.ex
mix.exs
mix.lock

We can get what we want out of Adz by using using stock Logger.
The significant change is that the module and line number of the log
sites are now given as key/value pairs, instead of `module:line`.
Additionally, timestamps are given in UTC, and it is much easier to add arbitrary new key/value pairs to the output in the future.
Previously, output looked like this:
```
2016-11-18T21:13:43.0641  (Cog.Command.Service.Memory:74) [info] Dead pipeline token clean up interval set to 30 seconds.
2016-11-18T21:13:43.0642  (Cog.Command.PermissionsCache:35) [info] Ready. Cache TTL is 10 seconds.
2016-11-18T21:13:43.0646  (Cog.Command.Pipeline.Initializer:31) [info] Ready.
2016-11-18T21:13:43.0732  (Phoenix.Endpoint.CowboyHandler:101) [info] Running Cog.Endpoint with Cowboy using …
```

Remove Adz

---

lib/cog/chat/hipchat/template_processor.ex
lib/cog/command/pipeline/executor.ex
lib/cog/error_response.ex
priv/templates/common/error.greenbar
test/cog/chat/hipchat/templates/common/error_test.exs
test/cog/chat/slack/templates/common/error_test.exs
test/cog/template/new/common_test.exs
test/cog/template/new/evaluator_test.exs
test/integration/command_test.exs
test/integration/hipchat_test.exs
test/integration/slack_test.exs
test/support/slack_client.ex

This PR does a few things:
1. Updates the attachment rendering for HipChat to be more consistent with Slack.
2. It flips the logic that we used to select planning vs. execution errors. I believe we have had these inverted for some time and effectively every error message was being reported as "The pipeline failed planning the invocation" even when it was a command execution failure. The screenshots below illustrate the problem
3. Updated the greenbar template for errors to move the error message to the top so that it isn't hidden by a _more_ link by Slack. Also moved the display of the failed command or pipeline plan to fields within the attachment instead of rendering them to text in the body of the error, also to prevent truncation. Screenshots below.
4. Increase the wait time between …

Improved error template + HipChat attachment rendering

---

config/config.exs
priv/templates/embedded/help-bundle.greenbar
priv/templates/embedded/help-command.greenbar
test/cog/chat/hipchat/templates/embedded/help_bundle_test.exs
test/cog/chat/slack/templates/embedded/help_bundle_test.exs

* Bundle Help
* Display command names in a fixed width font.
* Move the Configuration section to the bottom, immediately before Author.
* Display the name of config env vars in a fixed width font.
* Command Help
* Display options and required options in a fixed width font.
* Bump embedded version bundle to pick up template changes.

Tweak help output for bundles and commands.

---

lib/cog/repository/groups.ex
test/controllers/v1/role_grant_controller_test.exs
web/controllers/v1/role_grant_controller.ex

Cog will now return an error when trying to remove the cog-admin role from the cog-admin group. Updates to flywheel, cogctl and cog-api to follow.
Note: Roles looks like it could use a refactor. Things have moved on a bit from when this code was first written. In addition to the error messaging, this PR moves the bulk of the grant/revoke role logic out of the controller and leverages the repository in preparation for a more complete refactor.
part of #825

return an error when trying to revoke cog-admin from the cog-admin group

---

docker-compose.yml
lib/cog/models/relay.ex

* Remove unnecessary env var now that `RELAY_MANAGED_DYNAMIC_CONFIG` defaults to true
* Downcase user provided relay ids

Sane defaults cleanup

---

lib/cog/models/command_version.ex
mix.lock
priv/repo/migrations/20161202162538_add_output_to_command_versions.exs
priv/templates/embedded/help-command.greenbar
web/views/command_version_help_view.ex

Bundle authors can now include an `output` attribute when defining a command which is printed in a new "Output" section for command help docs.
Example:
Closes #953

Command output docs

---

.buildkite/pipeline.yml

While we investigate transient timeout-related failures in our HipChat
CI tests, we'll disable the tests to prevent spurious CI failures.

Temporarily disable HipChat tests in CI

---

lib/cog/chat/slack/formatter.ex
test/integration/slack_test.exs

`Regex.run` was returning incorrect indices when unicode was present. Instead of fixing that up, we can just switch to `Regex.replace`.
Fixes #1161

Use Regex.replace to format Slack messages

---

CHANGELOG.md

Issue 1160 was closed because we ended up not doing it, not because we
merged any code.
Issue 1226 was added to the 0.16.2 release enhancement list. I'd
forgotten to create an issue for it at the time, which caused it to slip
through our changelog-generation logic. (The code was cherry-picked into
0.16.2 in commit 05436392)

Fix changelog for 0.17.0, 0.16.2

---

mix.lock
priv/templates/embedded/trigger-info.greenbar
priv/templates/embedded/trigger-list.greenbar
test/cog/chat/hipchat/templates/embedded/trigger_info_test.exs
test/cog/chat/slack/templates/embedded/trigger_info_test.exs

Treat the pipeline as a fixed-width string, but use new Greenbar that
does not render fixed-width directives as such when already in a
fixed-width block. This ensures consistent results in Slack and
HipChat.
Fixes #1239

Render trigger pipelines correctly in chat output

---

lib/cog/command/pipeline/executor.ex
lib/cog/events/api_event.ex
lib/cog/events/pipeline_event.ex
lib/cog/events/util.ex
web/plugs/util.ex

Previously, the timestamps we generated for Cog's event log had only
second resolution, despite the fact that events frequently occur at the
microsecond scale. This made it more complicated that it should be to
order events (e.g., when analyzing data using a log aggregator).
Now, we log using ISO8601 timestamps with microsecond resolution.
In the course of making this change, lots of time-related code was
removed, in favor of native Elixir code (which didn't exist when the
code was initially written). We still need to have custom code to
compute `DateTime` differences, though. Sigh.
It was also discovered that our elapsed microsecond event log data
didn't quite line up with the timestamps we were printing; this is
because we weren't being consistent with what we were using as our basis
of …

Increase event timestamp precision and accuracy

---

lib/cog/command/pipeline/destination.ex
lib/cog/command/pipeline/executor.ex
lib/cog/command/reply_helper.ex
test/cog/command/pipeline/destination_test.exs
test/controllers/v1/trigger_execution_controller_test.exs
web/controllers/v1/trigger_execution_controller.ex

Now we formally classify redirection destinations according to how the
output needs to be rendered. We have three types of output currently:
* chat: a chat adapter destination. Output is rendered through
Greenbar templates.
* trigger: output destined for trigger destinations. Output is *not*
rendered through Greenbar, but embeded in a map with additional
information. The keys are as follows:
status: Either "success", "abort", or "error"
pipeline_output: the output of the pipeline.
message: explanatory message for "abort" or "error" responses.
The only trigger adapter currently is the "http" adapter. The
response statuses map to the following HTTP codes:
success: 200
error: 500
abort: 422
* status_only: an abbreviated version of trigger-style output,
containing only "status" and …

Refactor pipeline output disposition

---

lib/cog/chat/user.ex

Chat users don't need first and last names in order to successfully
execute a pipeline.
Fixes #1245

Relax validation constraints on chat users

---

lib/cog/events/api_event.ex
lib/cog/events/pipeline_event.ex

Removes the `data` map field from each event type. Now, all events are
simply flat maps, which should make ingesting them into aggregation
software (e.g. Logstash, Splunk) more straightforward.
Internally, we're just using maps instead of structs, though we still
maintain centralized control of how the maps are generated, so they
should be self-consistent.
Note that the order of the fields in the printed JSON in the log file
will not be deterministic (these are maps, not structs), so you'll need
to take that into account if you're rolling your own log analysis
tooling. Treat each line like a JSON map, though, and you'll be fine.
Fixes #1255

Simplify audit log events

---

lib/cog/models/trigger.ex
lib/cog/models/user.ex
lib/cog/repository/users.ex
priv/repo/migrations/20161220162331_trigger_user_referential_integrity.exs
test/cog/models/trigger_repo_test.exs
test/cog/repository/triggers_test.exs
test/commands/trigger/create_test.exs
test/controllers/v1/trigger_controller_test.exs
test/controllers/v1/trigger_execution_controller_test.exs
test/controllers/v1/user_controller_test.exs
web/controllers/v1/user_controller.ex

If you attempt to delete a user that is currently associated with any
triggers (i.e., that user is the one the triggers run as), the request
will be blocked.
This will prevent triggers from breaking when users are deleted,
allowing operators to re-wire their triggers as appropriate.
Fixes #1246

Link triggers and their users via FK constraint

---

lib/cog.ex
lib/cog/commands/bundle/info.ex
lib/cog/commands/help.ex
lib/cog/repository/bundles.ex
mix.lock
priv/templates/embedded/bundle-info.greenbar
priv/templates/embedded/bundle-versions.greenbar
priv/templates/embedded/help-bundles.greenbar
test/cog/chat/hipchat/templates/embedded/bundle_info_test.exs
test/cog/chat/slack/templates/embedded/bundle_info_test.exs
test/cog/chat/slack/templates/embedded/help_bundles_test.exs
test/cog/repository/bundles_test.exs
test/controllers/v1/bundle_version_controller_test.exs
test/controllers/v1/bundles_controller_test.exs
test/support/command_case.ex
test/support/model_case.ex
test/support/util.ex
web/controllers/v1/bundle_status_controller.ex
web/views/bundle_version_view.ex
web/views/bundles_view.ex

This moves a lot of the post startup bits to a separate module and adds additional logic to disable old incompatible bundles. It also prevents incompatible bundles from being re-enabled.
part of #1262 
depends on https://github.com/operable/spanner/pull/88

Disable and disallow enabling of incompatible bundle versions

---

lib/carrier/messaging/connection.ex
lib/carrier/messaging/connection_sup.ex
lib/carrier/messaging/gen_mqtt.ex
lib/carrier/messaging/tracker.ex
lib/cog.ex
lib/cog/chat/hipchat/provider.ex
lib/cog/chat/http/provider.ex
lib/cog/chat/slack/provider.ex
lib/cog/command/gen_command.ex
lib/cog/command/pipeline/executor.ex
lib/cog/command/pipeline/initializer.ex
lib/cog/relay/info.ex
lib/cog/relay/relays.ex
lib/cog/util/debug.ex
test/carrier/messaging/tracker_test.exs
test/controllers/v1/bundle_version_controller_test.exs
test/support/fake_relay.ex
test/support/snoop.ex
test/support/test_provider.ex

Refactored `Carrier.Messaging.Connection` so multiple Erlang/Elixir processes can share
a single connection. The connection keeps track of subscribers and GenMqtt-style reply endpoints and ensures correct delivery of messages including support for `+` and `*` topic wildcards. `Connection` places monitors on all subscribing processes allowing it to clean up subscriptions after subscribers crash.
These changes are in preparation for the new executor design based on GenStage. Attempting to share a single connection between stages for the same pipeline didn't integrate well with GenMqtt causing Cog to use transient MQTT connections and incurring a small, but noticeable,
performance penalty.
Centralizing connection sharing logic in the connection itself resolves all previous problems and …

Share MQTT connections between processes

---

lib/cog/commands/info.ex
priv/templates/embedded/info.greenbar
test/cog/chat/hipchat/templates/embedded/info_test.exs
test/cog/chat/slack/templates/embedded/info_test.exs

Adds a simple info command for cog
resolves #1284

cog info command

---

lib/cog/bundle/config.ex
lib/cog/command/gen_command/base.ex
lib/cog/commands/help.ex
lib/cog/commands/helpers.ex
lib/cog/models/command_version.ex
mix.lock
priv/repo/migrations/20170106205545_remove_subcommands_from_command_versions.exs
priv/templates/embedded/help-command.greenbar
web/views/command_version_help_view.ex

Subcommands are still present in the v4 bundle configs (which can still be installed) but they will no longer be shown in the help documentation or otherwise supported. They have been completely removed from v5 bundle configs.
https://github.com/operable/cog/issues/1204

Remove subcommands from codebase

---

lib/carrier/messaging/connection.ex

Wraps logic creating link between `Connection` and its owning process with a `try/rescue` block. Detects when the owner process has exited before the connection is fully set up.
Prevents long stacktraces from polluting Cog's log output. I noticed this happening over the weekend when Slack integration tests run.

Handle exited connection owners

---

lib/carrier/messaging/connection.ex
mix.exs
mix.lock

Companion PR: https://github.com/operable/go-relay/pull/68
Fixes https://github.com/operable/cog/issues/874

Compress all mqtt traffic with snappy

---

lib/cog/pipeline/relay_selector.ex

Fixes #1314 
* Correctly outputs error when no relay groups are assigned a bundle
* Correctly outputs error when no relays are available to run a bundle

Return relay errors as the error module expects

---

lib/cog/models/group.ex
lib/cog/repository/groups.ex
test/commands/group/member/remove_test.exs
test/controllers/v1/group_membership_controller_test.exs
test/support/database_assertions.ex
web/views/groups_view.ex

This just changes the user and role associations to many-to-many, which reduces some of the extra unnecessary bits on the model.

group many-to-many associations

---

lib/cog/models/user.ex
priv/repo/migrations/20170118183141_protect_last_admin_group_membership.exs
test/controllers/v1/group_membership_controller_test.exs
web/controllers/v1/group_membership_controller.ex

Now that the admin user can have any username, change our cog-admin
group protection trigger to prohibit removing the last member rather
than specifically checking for the "admin" username.

Protect the last user in the cog-admin group

---

lib/cog/chat/adapter.ex
lib/cog/command/gen_command.ex
lib/cog/commands/history.ex
lib/cog/commands/history/exec.ex
lib/cog/commands/pipeline/info.ex
lib/cog/commands/pipeline/kill.ex
lib/cog/commands/pipeline/list.ex
lib/cog/commands/pipeline/util.ex
lib/cog/messages.ex
lib/cog/models/pipeline_history.ex
lib/cog/models/types/process_id.ex
lib/cog/pipeline.ex
lib/cog/pipeline/execution_stage.ex
lib/cog/pipeline/tracker.ex
lib/cog/pipeline_core_sup.ex
lib/cog/repository/pipeline_history.ex
mix.exs
priv/repo/migrations/20170120141008_add_pipeline_history.exs
priv/templates/embedded/history-list.greenbar
priv/templates/embedded/pipeline-info.greenbar
priv/templates/embedded/pipeline-kill.greenbar
priv/templates/embedded/pipeline-list.greenbar
test/cog/chat/hipchat/templates/embedded/history_list_test.exs
test/cog/chat/hipchat/templates/embedded/pipeline_info_test.exs
test/cog/chat/hipchat/templates/embedded/pipeline_kill_test.exs
test/cog/chat/hipchat/templates/embedded/pipeline_list_test.exs
test/cog/chat/slack/templates/embedded/history_list_test.exs
test/cog/chat/slack/templates/embedded/pipeline_info_test.exs
test/cog/chat/slack/templates/embedded/pipeline_kill_test.exs
test/cog/chat/slack/templates/embedded/pipeline_list_test.exs

This PR adds several commands aimed at helping users manage pipeline execution and their command history a la standard Unix shell behaviors. The commands are:
* `pipeline list` - `ps`-style command for viewing pipeline status
* `pipeline info` - Displays detailed information about a specific pipeline
* `pipeline kill` - Aborts an executing pipeline
* `history` - Lists user's command history
* `history exec` - Re-executes a previous command history entry
Pipeline information is stored in the DB and retained essentially forever. Commands which list data, like `pipeline list` and `history`, limit the number of entries to 20 unless the user specifies otherwise. Pipeline process information is also stored in the DB, which is a little odd, but avoids having to keep two data stores in sync (DB …

Added pipeline management commands

---

lib/cog/models/group.ex
lib/cog/models/group_role.ex
lib/cog/models/permission.ex
lib/cog/models/relay.ex
lib/cog/models/relay_group.ex
lib/cog/models/role.ex
lib/cog/models/user.ex
lib/cog/repository/bundles.ex
lib/cog/repository/relays.ex
priv/repo/migrations/20170123141709_convert_cascade_references_to_restrict.exs
test/cog/bootstrap_test.exs
test/cog/group_test.exs
test/cog/models/permission_test.exs
test/cog/models/relay_group_test.exs
test/cog/models/relay_test.exs
test/cog/role_test.exs
test/cog/user_test.exs
test/controllers/v1/relay_controller_test.exs
web/controllers/v1/relay_controller.ex

Instead of restricting on delete for all foreign key relations, it made sense to only restrict relations that can be manually modified via the api. The main exception is the tree of bundle relations, so when a bundle is deleted we still cascade and delete all associated child records. To cleanly delete bundles, permissions are unlinked from any roles they had been granted to first. All exceptions raised are returned as errors on the id attribute since there's no other key that would really make sense to hang it off of.
Closes https://github.com/operable/cog/issues/794

Restrict deletion on group and relay group relations

---

lib/cog/models/group.ex
test/commands/group/info_test.exs

Replaces the users key with a members key when encoding a group to json. Fixes the bug with group info not returning associated members.
resolves #1332

fix group chat command

---

lib/cog/models/role.ex
lib/cog/repository/roles.ex
test/controllers/v1/role_controller_test.exs
web/controllers/v1/role_controller.ex

If trying to delete a role via the API, the server will response with a `422` and the body: `{"errors":{"id":["cannot delete role that has been granted permissions"]}}` instead of throwing an exception.
Fixes https://github.com/operable/cog/issues/1336

Catch constraint errors on role delete

---

lib/cog.ex
lib/cog/command/gen_command.ex
lib/cog/commands/abort_when.ex
lib/cog/db_sup.ex
lib/cog/pipeline.ex
lib/cog/pipeline/error_sink.ex
lib/cog/pipeline/execution_stage.ex
lib/cog/pipeline/output_sink.ex
lib/cog/pipeline/signals.ex
lib/cog/repository/pipeline_history.ex
priv/templates/common/abort.greenbar
test/integration/abort_test.exs
test/support/snoop.ex

Support for command aborts were omitted in initial `Executor` re-work. I suspect our lack of test coverage for aborts had a lot to do with why this happened. This PR restores abort support and adds test coverage.
Fixes #1340

Support command aborts

---

lib/cog/commands/seed.ex
test/integration/command_test.exs

Fixes `Cog.Command.Seed` crash triggered when given a string containing escaped double quotes.
Fixes #1323

Replace escaped double quotes with double quotes

---

.buildkite/pipeline.sh

Until we level-up the new Python-based cogctl tests to hit a live Cog
server, dependent builds aren't going to do anything for us but eat up
build agents.

Disable dependent cogctl build

---

lib/cog/repository/groups.ex
lib/cog/repository/users.ex
web/controllers/v1/password_reset_controller.ex

This should resolve #998. There were some questions about potentially rewording the email a bit, but I'm not sure that that is really a major issue at this point.

fail more gracefully when smtp isn't configured properly

---

.buildkite/pipeline.sh

While we sort out issues pertaining to getting the new Python cogctl
incorporated into the Cog image build, we'll disable this step of the
pipeline.

Temporarily disable image building

---

Dockerfile
Makefile

Streamline the Dockerfile, getting rid of things we never used, removing some unnecessary and costly operations, and leverage the Docker cache for quicker builds.
It's also smaller!

Refactor the Dockerfile

---

lib/cog/models/chat_handle.ex
test/cog/models/chat_handle_repo_test.exs

If another user has already claimed a given chat handle, deal with the
error gracefully, instead of crashing the web controller.

Check assigning a chat handle to more than one user

---

lib/cog/commands/pipeline/info.ex
lib/cog/commands/pipeline/kill.ex
lib/cog/commands/pipeline/list.ex
test/commands/permission/list_test.exs
test/commands/pipeline/info_test.exs
test/commands/pipeline/kill_test.exs
test/commands/pipeline/list_test.exs
test/controllers/v1/permission_controller_test.exs
test/support/command_case.ex

Adds a hardcoded permission to the pipeline command limiting who can manage pipelines to the owning user and users with the `operable:manage_user_pipeline` permission.
resolves #1327

secure pipeline command

---

.travis.yml
test/integration/slack_registration_test.exs
test/integration/slack_test.exs
test/integration/slack_threads_test.exs
test/support/slack_client.ex

It appears that Slack is now sending recently-sent messages to a client
when it connects. That is, it's possible to receive messages sent before
you actually connect. This was causing lots of random failures in the
tests, because we would end up making assertions on messages sent in
response to previous tests! The actual functionality of the Slack
provider was fine; this was purely a testing issue.
Many changes were made to clean and tighten up the tests (detailed
below), but the big take-home is that we now pay attention to message
timestamps to determine whether to process a message or not.
An overview of what was done:
* Run Slack tests in Travis CI
* Create a Slack client once per Slack suite, as opposed to once per
Slack *test*.
Though not strictly necessary, this reduces the chances …

Get Slack tests working again

---

README.md

This prevents the security warning, and fixes #1386 until a certificate solution is implemented.

Change Cog-Book URLs in README to unsecure

---

.travis.yml

Unit and Slack integration tests work, but some timeout issues need to
be tracked down on the HipChat side of things. See #1395 for more.
We can disable the HipChat tests for now, so we can benefit from Travis
CI builds on other PRs.

Disable HipChat integration tests for now

---

config/config.exs

Simple change to at least allow a flexible global pipeline command timeout at runtime.
This is a minor part of https://github.com/operable/cog/issues/1283 but that ticket will need to be revisited with a full planning of how to implement the real feature.

Allow COG_PIPELINE_TIMEOUT to set the timeout at runtime

---

config/config.exs
lib/cog/commands/count.ex
test/commands/count_test.exs

First attempt at a count command.
Mostly just took what was already in mix/max and changed it slightly.
Not sure if I'm totally on board with the current state.
If you pass in something like:
```seed '[{}]' | count```
It will return 0, due to how Cog passes in the `cog_env` param (otherwise, just running `count` would result in a 1).
At the moment there are no error cases.
Thoughts/suggestions appreciated.
This would potentially handle https://github.com/operable/cog/issues/772

Add operable:count command

---

README.md

The invite app is kaput, so here's a permanent invite link.
Fixes #1409

Update Cog Community Slack signup URL

---

lib/cog/bundle/warehouse.ex

This will allow us to temporarily point the warehouse at this gh-pages static site until we can figure out what to do with the warehouse.

Temporarily point warehouse to static site

---

README.md

cog-book.operable.io is defunct, moved to book.cog.bot!

cog-book.operable.io links to book.cog.bot

---

lib/cog/command/service/chat.ex
lib/cog/repository/services.ex
test/controllers/v1/chat_service_controller_test.exs
test/support/test_provider.ex
web/controllers/v1/chat_service_controller.ex
web/service_router.ex

I've taken what Mark started and just added some tests for it.
This adds a chat service endpoint so you can post message back to the user/channel (or a specific user/channel if desired).
Will add docs on its usage, but it's just a POST to /v1/services/chat/1.0.0/send_message  with a destination channel/user and a message. 
Right now if the user wants to respond back directly they'd need to find out if the COG_ROOM was "direct", if so set the destination as @${COG_CHAT_HANDLE}, otherwise use #${COG_ROOM}. In the future i'd like to update the relay to set a COG_INITIATOR or something which decides this for you.

Chat service POC
