operable/cog

.dockerignore
Dockerfile
docker-compose.yml
scripts/wait-for-it.sh

* Clean up Dockerfile and include cogctl
* Add docker-compose for running a full environment
* Add simple script to wait for network services to be up

add docker and docker-compose

---

lib/cog.ex

VM sanity check

---

lib/cog/command/alias_expander.ex
lib/cog/command/command_resolver.ex
lib/cog/command/pipeline/executor.ex
lib/cog/commands/help.ex
lib/cog/queries/alias.ex
lib/cog/queries/command.ex

See commit messages for details. Much of this is preparatory for the executor rewrite. Work will be done to make this more efficient, but that's all tied up in the rewrite.

Adjust alias search algorithm

---

lib/cog.ex

We should verify that schema migrations are up-to-date when starting Cog. This is being done after we verify that SMP and dirty-schedulers were included in the build. We must perform this verification after the Cog database comes up since we need to verify that everything has been migrated in the database.
If we can get a `migration_needed?()` function in Ecto, then we can replace this one with the embedded one that could possibly verify that each migration was actually executed. 
I also refactored making the logging of the verifications.
Fixes #363

Issue #363: Verify that schema migrations have taken place and are up to date

---

config/config.exs
config/dev.exs
config/helpers.exs

Enable spoken commands via env var

---

lib/cog/command/pipeline/executor.ex

Closes https://github.com/operable/cog/issues/275

Replace smart quotes with ascii quotes

---

lib/cog/command/pipeline/executor.ex

Match correct atom for variable binding errors

---

lib/cog/adapters/slack/rtm_connector.ex

The Slack library we're using has the top-level module name `Slack`,
which is the same as the alias we were using for
`Cog.Adapters.Slack`. While this didn't cause code problems, it did make
it very confusing to read and understand the code, because it wasn't
immediately clear if a function came from the library or the adapter.

Use different alias for Slack adapter

---

lib/cog.ex

I was in the code for some other stuff and took the opportunity to do
some refactoring. This cleans up the migration check logic, provides
more detailed messages, and removes some unnecessary helper
functions (`abort_cog/0` and `log_message/2`).

Streamline migration check code

---

mix.lock

reference https://github.com/operable/cog/issues/413

spanner bump

---

lib/cog/bundle/install.ex
lib/cog/models/bundle.ex
lib/cog/relay/relays.ex
priv/repo/migrations/20160404191532_remove_manifest_file_from_bundle.exs
web/controllers/v1/bundle_deploy_controller.ex
web/router.ex

This is a WIP
This is the initial work for the bundle deployment endpoint.
TODO:

WIP: bundle deployment endpoint

---

test/controllers/v1/user_controller_test.exs
web/controllers/v1/user_controller.ex
web/views/user_view.ex

This PR adds roles and their corresponding permissions into the user output. 
Fixes https://github.com/operable/cog/issues/514

Roles in Users

---

lib/cog/command/pipeline/executor.ex
test/controllers/v1/trigger_execution_controller_test.exs

If our pipeline has "run dry" at any point, we'll send a
response back to all destinations, but only if the pipeline was
initiated from chat.
If it was initiated from a trigger, though, we don't want to
output to any chat destinations. Otherwise, you'd end up with
"mystery" messages saying "Pipeline succeeded but there was no
output!" without indication of what's going on. If we trigger
something that succeeds without output, we'll just be silent in
chat.
Additionally, we now terminate the pipeline early if output is ever
empty, instead of waiting until the end.

Send early-termination output only if chat-initiated

---

test/controllers/v1/role_controller_test.exs
web/controllers/v1/role_controller.ex
web/controllers/v1/role_grant_controller.ex
web/views/roles_view.ex

This PR adds groups into the roles resource. 
Fixes https://github.com/operable/cog/issues/525

Add groups to roles

---

lib/cog/models/bundle.ex
lib/cog/models/join_table.ex
lib/cog/models/relay.ex
lib/cog/models/relay_group.ex
test/controllers/v1/relay_group_membership_controller_test.exs
web/controllers/v1/relay_group_membership_controller.ex
web/router.ex
web/views/relay_group_view.ex

We were crashing when trying to add bundles that already existed in the group to relay groups. This rescues from the crash and returns a message to the user.

Implement Groupable for relay groups

---

config/config.exs
lib/cog.ex
lib/cog/command/command_sup.ex
lib/cog/command/pipeline_sup.ex
lib/cog/repository/services.ex
lib/cog/service_endpoint.ex
priv/swagger/services/memory.yaml
test/cog/repository/services_test.exs
test/controllers/v1/memory_service_controller_test.exs
test/controllers/v1/services_controller_test.exs
test/views/service_view_test.exs
web/controllers/v1/memory_service_controller.ex
web/controllers/v1/service_controller.ex
web/plugs/service_authentication.ex
web/plugs/util.ex
web/service_router.ex
web/views/service_view.ex

Service metadata API + Memory Service

---

lib/cog/command/pipeline/executor.ex
lib/cog/command/pipeline/plan.ex
lib/cog/command/pipeline/planner.ex
lib/cog/command/request.ex

This implements the cog parts of https://github.com/operable/cog/issues/618

Include stage_pos in plan and eventually command request

---

lib/cog/bundle/config.ex
lib/cog/bundle/install.ex
lib/cog/command/gen_command/base.ex
test/cog/bundle/config_test.exs
test/support/test_commands/bad_template.ex
test/support/test_commands/required_opt_test_command.ex
test/support/test_commands/test_echo.ex
test/support/test_commands/types_test_command.ex

remove enforcing from gen_command and install

---

lib/cog/bundle/config.ex
lib/cog/bundle/install.ex
lib/cog/command/gen_command/base.ex
lib/cog/command/pipeline/planner.ex
lib/cog/commands/raw.ex
lib/cog/models/command.ex
priv/repo/migrations/20160506203250_remove_command_execution.exs
test/cog/bundle/config_test.exs
test/cog/command/pipeline/planner_test.exs
test/support/executor_helpers.ex
web/views/commands_view.ex

Kill execution with :fire:

---

lib/cog/commands/alias.ex
lib/cog/commands/alias/ls.ex
lib/cog/commands/alias/mv.ex
lib/cog/commands/alias/new.ex
lib/cog/commands/alias/rm.ex
lib/cog/commands/bundle.ex
lib/cog/commands/echo.ex
lib/cog/commands/filter.ex
lib/cog/support/model_utilities.ex
test/integration/commands/bundle_test.exs
test/integration/commands/echo_test.exs
test/integration/commands/filter_test.exs

This standardizes usage info and adds tests when necessary for alias, bundle, echo, filter.
reference #612

updates to usage info and tests for alias, bundle, echo, filter

---

lib/cog/commands/group.ex
lib/cog/commands/help.ex
lib/cog/commands/max.ex
lib/cog/commands/min.ex
lib/cog/commands/permissions.ex
test/integration/commands/group_test.exs
test/integration/commands/help_test.exs
test/integration/commands/max_test.exs
test/integration/commands/min_test.exs
test/integration/commands/permission_test.exs

Updates usage to roughly follow the same pattern and adds tests where necessary.
reference #612

Usage updates and tests for group, help, max, min, permissions

---

lib/cog/commands/raw.ex
lib/cog/commands/relay.ex
lib/cog/commands/relay/list.ex
lib/cog/commands/relay/update.ex
lib/cog/commands/relay_group.ex
lib/cog/commands/relay_group/add.ex
lib/cog/commands/relay_group/assign.ex
lib/cog/commands/relay_group/create.ex
lib/cog/commands/relay_group/delete.ex
lib/cog/commands/relay_group/info.ex
lib/cog/commands/relay_group/remove.ex
lib/cog/commands/relay_group/rename.ex
lib/cog/commands/relay_group/unassign.ex
lib/cog/commands/role.ex
test/integration/commands/role_test.exs

Updates usage and adds test where necessary for raw, relay, relay_group and role.
reference #612

Usage and tests for raw, relay, relay_group, role

---

lib/cog/commands/rules.ex
lib/cog/commands/seed.ex
lib/cog/commands/sleep.ex
lib/cog/commands/sort.ex
lib/cog/commands/sum.ex
lib/cog/commands/table.ex
lib/cog/commands/unique.ex
lib/cog/commands/wc.ex
lib/cog/commands/which.ex
test/integration/commands/rule_test.exs
test/integration/commands/seed_test.exs
test/integration/commands/sleep_test.exs
test/integration/commands/sort_test.exs
test/integration/commands/sum_test.exs
test/integration/commands/unique_test.exs
test/integration/commands/wc_test.exs

Updates usage and adds tests when necessary for sum, table, unique, wc and which.
reference #612

updates to usage and tests for sum, table, unique, wc, which

---

lib/cog/commands/max.ex
lib/cog/commands/min.ex
test/integration/commands/max_test.exs
test/integration/commands/min_test.exs
test/integration/commands/sort_test.exs

Changed the args a little bit after talking to @mpeck since you'll probably always want to select an entire input item and not just a value.
Closes #673 
Closes #674

Rework min and max

---

lib/cog/repository/groups.ex
test/controllers/v1/group_controller_test.exs
web/controllers/v1/group_controller.ex
web/controllers/v1/group_membership_controller.ex

This creates a groups repository and updates the group and group membership controllers accordingly. This is a prereq for https://github.com/operable/cog/issues/671

Create group repository

---

lib/cog/repository/users.ex
test/controllers/v1/user_controller_test.exs
web/controllers/v1/user_controller.ex

Moves user bits into a users repository
prereq for #671

User's repository

---

test/controllers/v1/bundle_version_controller_test.exs
web/views/command_version_view.ex

Add ID and doc strings to command version view

---

lib/cog/repository/bundles.ex

This commit causes Cog to delete and rebuild the embedded bundle at boot whenever `Mix.env == :dev`.
Fixes #721

Delete & recreate embedded bundle

---

lib/cog/repository/bundles.ex
test/cog/repository/bundles_test.exs
test/controllers/v1/bundles_controller_test.exs

Filter site bundle from repository.Bundles output

---

test/controllers/v1/bundles_controller_test.exs
web/controllers/v1/bundles_controller.ex

Add a location header on new bundle responses

---

lib/carrier/messaging/connection.ex
lib/cog/command/pipeline/executor.ex

Chat adapters can have limits on the size of message they will
accept. While a complete solution will deal with this in an
adapter-specific manner (breaking long messages into multiple messages,
using an alternative format, etc.), we can at least log a message when
we see a message that is potentially "too big".
Here, we add a new option recognized by
`Carrier.Messaging.Connection.publish/3` that lets a caller specify a
size threshold in bytes. If the JSON-encoded message is larger than this
threshold, we emit a log warning.
Fixes #739

First stab at handling overly large chat responses

---

lib/cog/bundle/embedded.ex
lib/cog/commands/trigger.ex
lib/cog/commands/trigger/create.ex
lib/cog/commands/trigger/delete.ex
lib/cog/commands/trigger/disable.ex
lib/cog/commands/trigger/enable.ex
lib/cog/commands/trigger/helpers.ex
lib/cog/commands/trigger/info.ex
lib/cog/commands/trigger/list.ex
lib/cog/commands/trigger/update.ex
lib/cog/repository/triggers.ex
lib/cog/templates/slack/trigger-create.mustache
lib/cog/templates/slack/trigger-delete.mustache
lib/cog/templates/slack/trigger-disable.mustache
lib/cog/templates/slack/trigger-enable.mustache
lib/cog/templates/slack/trigger-info.mustache
lib/cog/templates/slack/trigger-list.mustache
priv/repo/migrations/20160615225508_default_trigger_timeout.exs
test/integration/commands/trigger_test.exs
web/controllers/v1/trigger_controller.ex

This brings the embedded bundle to parity with `cogctl` with respect
to trigger manipulation.
Fixes: #771

Add `operable:trigger` command

---

lib/cog/commands/rule.ex
lib/cog/commands/rule/delete.ex
lib/cog/templates/slack/rule-delete.mustache
lib/cog/templates/slack/rule-drop.mustache
test/integration/commands/rule_test.exs

`rule drop` => `rule delete`

---

lib/cog/models/bundle.ex
lib/cog/models/bundle_version.ex
lib/cog/models/bundle_version_permission.ex
lib/cog/models/command.ex
lib/cog/models/command_version.ex
lib/cog/models/join_table.ex
lib/cog/models/permission.ex
lib/cog/models/rule.ex
lib/cog/models/rule_bundle_version.ex
lib/cog/repository/bundles.ex
priv/repo/migrations/20160628193728_remove_pre_bundle_version_tables.exs
priv/repo/migrations/20160628204409_rename_v2_tables.exs

Nukes unused tables and drops `_v2` suffix.

Nuke pre bundle version tables

---

docs/commands.md
lib/cog/models/command.ex
lib/cog/models/command_opt.ex
lib/cog/models/command_version.ex
lib/cog/models/permission.ex
lib/cog/models/rule.ex
lib/cog/models/token.ex
lib/cog/repository/bundles.ex
lib/cog/repository/permissions.ex
priv/repo/migrations/20151028025449_add_ssh_adapter.exs
priv/repo/migrations/20160401212441_insert_fallback_templates.exs
priv/repo/migrations/20160406172300_insert_error_templates.exs
priv/repo/migrations/20160411203730_add_version_to_bundles.exs
test/cog/command/service/memory_test.exs
test/cog/models/ecto_json_test.exs

Depends on https://github.com/operable/cog/pull/831 but I can rebase if we don't want to merge that.

Fix remaining ecto warnings

---

lib/cog/audit_message.ex
lib/cog/command/pipeline/executor.ex

Implements the Cog part of the design described in #691.
Fixes #691

Allow commands to abort pipeline execution

---

lib/cog/adapters/slack/rtm_connector.ex

Use first word to detect mention name

---

web/controllers/v1/trigger_execution_controller.ex

The Amazon Simple Notification service sets the `Content-Type` to `text/plain` for all `POST` requests, despite the fact that it sends a JSON payload. This PR forces the `Content-Type` to be `application/json` when we detect the SNS user agent for `POST` requests to the Trigger endpoint.

force content-type of application/json for amazon sns

---

lib/cog/repository/groups.ex
priv/repo/migrations/20160803181844_replace_username_with_slack_handle.exs
test/controllers/v1/group_membership_controller_test.exs
test/controllers/v1/token_controller_test.exs
web/controllers/v1/token_controller.ex

* Allow users to retrieve a token with email address instead of username
* Identify group members by username

Username and/or email changes for flywheel

---

lib/cog/repository/users.ex
test/views/email_view.exs
web/controllers/v1/password_reset_controller.ex
web/templates/email/reset_password.text.eex
web/views/email_view.ex

Just a couple tweaks for password resets

password reset tweaks

---

lib/cog/command/pipeline/planner.ex
mix.lock
test/controllers/v1/trigger_execution_controller_test.exs
test/integration/alias_execution_test.exs
test/integration/command_test.exs

Prevent non-scalar variable bindings

---

lib/cog/permissions/eval/contain_expr.ex
mix.lock
test/cog/permissions/eval_test.exs

Added support for using named options with in permission exprs

---

lib/cog/repository/bundles.ex
test/controllers/v1/dynamic_config_controller_test.exs
web/controllers/v1/bundle_dynamic_config_controller.ex

Catch Ecto exception and use Cog.ChangesetView to render it.
Fixes #867

Improve dynamic config err msg

---

lib/cog/command/pipeline/executor.ex

Previously, if a command aborted the pipeline, we would end up
crashing in the executor. When we introduced the new templates, we
added a guard to the `respond` function. When we processed an aborted
command, we weren't capturing the information needed to satisfy the
guard.

Aborts no longer crash the executor

---

lib/cog/chat/slack/connector.ex
test/integration/slack_test.exs

Removed edited command support

---

lib/cog/commands/help.ex
priv/templates/embedded/help-bundle.greenbar
test/cog/chat/hipchat/templates/embedded/help_bundle_test.exs
test/cog/chat/slack/templates/embedded/help_bundle_test.exs

In order to make this work we have to massage the data a bit, making commands a list instead of a map. Maybe a tag in greenbar for iterating over a map would be useful?

Render bundle help using the bundle's config file

---

lib/cog/chat/slack/provider.ex

Validate Slack API token before use

---

.buildkite/hooks/post-command

Kick off a cogctl build at the end of a cog build

---

config/config.exs
lib/cog/command/pipeline/executor.ex
test/controllers/v1/trigger_execution_controller_test.exs

Makes command timeouts configurable

---

lib/cog/command/option_interpreter.ex

What it says on the tin.
Fixes #1097

Allow lists to bind to options of type list

---

mix.exs
mix.lock

Pick up elixir-slack fix for stale channel info

---

lib/cog/chat/hipchat/connector.ex
lib/cog/chat/hipchat/rooms.ex

Make sure room names are properly escaped

---

lib/cog/chat/slack/connector.ex

Tell Slack to linkify all @-mentions

---

test/commands/trigger_test.exs

trigger test updates

---

mix.exs
test/commands/bundle_test.exs

Updates and re-enables bundle command tests
part of #1122

bundle test rework

---

test/commands/sleep_test.exs

updates and additions to sleep tests
part of #1122

sleep test updates

---

lib/cog/support/model_utilities.ex
test/commands/group_test.exs

group test updates

---

test/commands/permission_test.exs
test/support/command_case.ex

update permission command tests

---

test/commands/echo_test.exs
test/commands/filter_test.exs
test/commands/max_test.exs
test/commands/min_test.exs
test/commands/unique_test.exs

re-enables echo, min, max, unique and filter
part of #1122

updates and re-enables echo and some of the smaller command tests

---

test/commands/relay_group_test.exs

relay group test updates

---

test/commands/relay_test.exs

relay test updates

---

test/commands/role_test.exs

role test updates

---

lib/cog/chat/slack/connector.ex

Reenable Slack ping/pong

---

lib/cog/chat/hipchat/template_processor.ex
test/cog/chat/hipchat/template_processor_test.exs
test/cog/chat/hipchat/templates/embedded/bundle_list_test.exs
test/cog/chat/hipchat/templates/embedded/bundle_versions_test.exs
test/cog/chat/hipchat/templates/embedded/permission_info_test.exs
test/cog/chat/hipchat/templates/embedded/permission_list_test.exs
test/cog/chat/hipchat/templates/embedded/relay_group_info_test.exs
test/cog/chat/hipchat/templates/embedded/relay_group_info_verbose_test.exs
test/cog/chat/hipchat/templates/embedded/relay_group_list_test.exs
test/cog/chat/hipchat/templates/embedded/relay_info_test.exs
test/cog/chat/hipchat/templates/embedded/relay_list_test.exs
test/cog/chat/hipchat/templates/embedded/role_info_test.exs
test/cog/chat/hipchat/templates/embedded/role_list_test.exs
test/cog/chat/hipchat/templates/embedded/rule_info_test.exs
test/cog/chat/hipchat/templates/embedded/rule_list_test.exs
test/cog/chat/hipchat/templates/embedded/trigger_info_test.exs
test/cog/chat/hipchat/templates/embedded/trigger_list_test.exs
test/cog/chat/hipchat/templates/embedded/user_group_info_test.exs
test/cog/chat/hipchat/templates/embedded/user_group_list_test.exs
test/cog/chat/hipchat/templates/embedded/user_group_list_verbose_test.exs
test/cog/chat/hipchat/templates/embedded/user_info_test.exs
test/cog/chat/hipchat/templates/embedded/user_list_handles_test.exs
test/cog/chat/hipchat/templates/embedded/user_list_test.exs
test/support/template_case.ex

render tables as text in HipChat

hipchat text tables

---

lib/cog/models/command_version.ex
mix.lock
priv/repo/migrations/20161202162538_add_output_to_command_versions.exs
priv/templates/embedded/help-command.greenbar
web/views/command_version_help_view.ex

Revert "Command output docs"

---

lib/cog/command/option_interpreter.ex
test/cog/command/option_interpreter_test.exs

Allow interpolated strings to be in list options

---

test/cog/command/service/data_store_test.exs

Since Mix / ExUnit start up the Cog application, and the `DataStore`
process is a registered one, we need to "swap out" that process for
tests.
This should be done for each test, swapping back the original process at
the end of each one.
Tests are also no longer run asynchronously, to prevent odd race
conditions.

Revise DataStoreTest setup

---

priv/templates/embedded/trigger-update.greenbar
test/cog/chat/hipchat/templates/embedded/trigger_update_test.exs
test/cog/chat/slack/templates/embedded/trigger_update_test.exs

Add trigger-update template

---

lib/cog/chat/adapter.ex

Fixes https://github.com/operable/cog/issues/1187

Ignore chat message that are only a command prefix

---

mix.lock

Mostly PR'd this to run CI. Will merge once green.

Bump greenbar for join scope fix

---

scripts/docker-start

Fixes https://github.com/operable/cog/issues/1301

Only generate profile if bootstrap vars present

---

lib/cog/permissions/eval/arg_opt.ex
lib/cog/permissions/eval/binary_expr.ex
lib/cog/permissions/eval/contain_expr.ex
mix.lock
test/cog/permissions/eval_test.exs

Closes https://github.com/operable/cog/issues/1209

Parse all in contain expression for list option in rules

---

lib/cog/chat/slack/provider.ex

Handle Slack connection failure

---

lib/cog/commands/history.ex
lib/cog/commands/pipeline/list.ex

use the user ID that we already have in the request.user map

---

lib/cog/commands/history.ex
lib/cog/repository/pipeline_history.ex
test/integration/history_test.exs

Fixed pipeline history range parsing errors

---

config/config.exs
lib/cog/pipeline/error_sink.ex
test/support/test_provider.ex

Add thread metadata to cmd abort support

---

lib/cog/events/api_event.ex
lib/cog/events/pipeline_event.ex

Fix timestamp in event log entries to be valid ISO8601

---

lib/cog/repository/pipeline_history.ex

This reduces some duplication in the pipeline history repository.
resolves #1326

dry up history repository a bit

---

lib/cog/commands/history.ex

* Limit 1 returns the expected result
* Negative limits cause an abort with error message
Fixes #1364

Fix history command bugs

---

README.md

Add Travis badge [skip ci]
